In [1]:
import pandas as pd
from datetime import datetime
import os
import numpy as np

In [2]:
file = pd.read_csv(os.path.join("..","..","Data","Raw","America_Health_Rankings","2017-Annual.csv"))
print(file)

       Edition  Report Type        Measure Name      State Name  Rank  Value  \
0         2017  2017 Annual       Air Pollution          Alaska  36.0    8.7
1         2017  2017 Annual       Air Pollution         Alabama  39.0    8.9
2         2017  2017 Annual       Air Pollution        Arkansas  16.0    7.2
3         2017  2017 Annual       Air Pollution         Arizona  46.0    9.7
4         2017  2017 Annual       Air Pollution      California  50.0   11.7
5         2017  2017 Annual       Air Pollution        Colorado  12.0    6.6
6         2017  2017 Annual       Air Pollution     Connecticut  35.0    8.6
7         2017  2017 Annual       Air Pollution        Delaware  43.0    9.1
8         2017  2017 Annual       Air Pollution         Florida  13.0    6.8
9         2017  2017 Annual       Air Pollution         Georgia  41.0    9.0
10        2017  2017 Annual       Air Pollution          Hawaii   6.0    5.9
11        2017  2017 Annual       Air Pollution            Iowa  25.0    7.8
12        2017  2017 Annual       Air Pollution           Idaho   6.0    5.9
13        2017  2017 Annual       Air Pollution        Illinois  49.0   10.2
14        2017  2017 Annual       Air Pollution         Indiana  46.0    9.7
15        2017  2017 Annual       Air Pollution          Kansas  18.0    7.3
16        2017  2017 Annual       Air Pollution        Kentucky  38.0    8.8
17        2017  2017 Annual       Air Pollution       Louisiana  25.0    7.8
18        2017  2017 Annual       Air Pollution   Massachusetts  10.0    6.2
19        2017  2017 Annual       Air Pollution        Maryland  41.0    9.0
20        2017  2017 Annual       Air Pollution           Maine  11.0    6.4
21        2017  2017 Annual       Air Pollution        Michigan  36.0    8.7
22        2017  2017 Annual       Air Pollution       Minnesota  20.0    7.5
23        2017  2017 Annual       Air Pollution        Missouri  33.0    8.3
24        2017  2017 Annual       Air Pollution     Mississippi  20.0    7.5
25        2017  2017 Annual       Air Pollution         Montana   9.0    6.0
26        2017  2017 Annual       Air Pollution  North Carolina  25.0    7.8
27        2017  2017 Annual       Air Pollution    North Dakota   2.0    4.2
28        2017  2017 Annual       Air Pollution        Nebraska  15.0    7.0
29        2017  2017 Annual       Air Pollution   New Hampshire   6.0    5.9
...        ...          ...                 ...             ...   ...    ...
37708     2017  2017 Annual  Water Fluoridation           Maine  21.0   79.3
37709     2017  2017 Annual  Water Fluoridation        Michigan  13.0   91.7
37710     2017  2017 Annual  Water Fluoridation       Minnesota   2.0   98.8
37711     2017  2017 Annual  Water Fluoridation        Missouri  26.0   76.8
37712     2017  2017 Annual  Water Fluoridation     Mississippi  37.0   60.0
37713     2017  2017 Annual  Water Fluoridation         Montana  46.0   33.7
37714     2017  2017 Annual  Water Fluoridation  North Carolina  18.0   87.8
37715     2017  2017 Annual  Water Fluoridation    North Dakota   4.0   96.7
37716     2017  2017 Annual  Water Fluoridation        Nebraska  29.0   71.6
37717     2017  2017 Annual  Water Fluoridation   New Hampshire  44.0   46.6
37718     2017  2017 Annual  Water Fluoridation      New Jersey  49.0   14.6
37719     2017  2017 Annual  Water Fluoridation      New Mexico  25.0   77.0
37720     2017  2017 Annual  Water Fluoridation          Nevada  28.0   73.7
37721     2017  2017 Annual  Water Fluoridation        New York  30.0   71.4
37722     2017  2017 Annual  Water Fluoridation            Ohio  11.0   92.7
37723     2017  2017 Annual  Water Fluoridation        Oklahoma  36.0   62.6
37724     2017  2017 Annual  Water Fluoridation          Oregon  48.0   22.6
37725     2017  2017 Annual  Water Fluoridation    Pennsylvania  41.0   54.6
37726     2017  2017 Annual  Water Fluoridation    Rhode Island  20.0   84.5
37727     2017  2017 Annual  Water Fluoridation  South Carolina   9.0   93.6
37728     2017  2017 Annual  Water Fluoridation    South Dakota   9.0   93.6
37729     2017  2017 Annual  Water Fluoridation       Tennessee  17.0   88.1
37730     2017  2017 Annual  Water Fluoridation           Texas  22.0   79.0
37731     2017  2017 Annual  Water Fluoridation            Utah  42.0   51.7
37732     2017  2017 Annual  Water Fluoridation        Virginia   7.0   95.9
37733     2017  2017 Annual  Water Fluoridation         Vermont  40.0   56.3
37734     2017  2017 Annual  Water Fluoridation      Washington  33.0   63.9
37735     2017  2017 Annual  Water Fluoridation       Wisconsin  16.0   88.9
37736     2017  2017 Annual  Water Fluoridation   West Virginia  14.0   90.5
37737     2017  2017 Annual  Water Fluoridation         Wyoming  39.0   57.1

       Score  Lower CI  Upper CI  \
0       0.06       NaN       NaN
1       0.19       NaN       NaN
2      -0.90       NaN       NaN
3       0.71       NaN       NaN
4       2.00       NaN       NaN
5      -1.29       NaN       NaN
6       0.00       NaN       NaN
7       0.32       NaN       NaN
8      -1.16       NaN       NaN
9       0.26       NaN       NaN
10     -1.74       NaN       NaN
11     -0.52       NaN       NaN
12     -1.74       NaN       NaN
13      1.03       NaN       NaN
14      0.71       NaN       NaN
15     -0.84       NaN       NaN
16      0.13       NaN       NaN
17     -0.52       NaN       NaN
18     -1.55       NaN       NaN
19      0.26       NaN       NaN
20     -1.42       NaN       NaN
21      0.06       NaN       NaN
22     -0.71       NaN       NaN
23     -0.19       NaN       NaN
24     -0.71       NaN       NaN
25     -1.68       NaN       NaN
26     -0.52       NaN       NaN
27     -2.00       NaN       NaN
28     -1.03       NaN       NaN
29     -1.74       NaN       NaN
...      ...       ...       ...
37708   0.21       NaN       NaN
37709   0.76       NaN       NaN
37710   1.07       NaN       NaN
37711   0.11       NaN       NaN
37712  -0.63       NaN       NaN
37713  -1.78       NaN       NaN
37714   0.59       NaN       NaN
37715   0.98       NaN       NaN
37716  -0.12       NaN       NaN
37717  -1.22       NaN       NaN
37718  -2.00       NaN       NaN
37719   0.11       NaN       NaN
37720  -0.03       NaN       NaN
37721  -0.13       NaN       NaN
37722   0.80       NaN       NaN
37723  -0.52       NaN       NaN
37724  -2.00       NaN       NaN
37725  -0.87       NaN       NaN
37726   0.44       NaN       NaN
37727   0.84       NaN       NaN
37728   0.84       NaN       NaN
37729   0.60       NaN       NaN
37730   0.20       NaN       NaN
37731  -0.99       NaN       NaN
37732   0.94       NaN       NaN
37733  -0.79       NaN       NaN
37734  -0.46       NaN       NaN
37735   0.64       NaN       NaN
37736   0.71       NaN       NaN
37737  -0.76       NaN       NaN

                                                  Source Source Year
0      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
1      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
2      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
3      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
4      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
5      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
6      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
7      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
8      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
9      U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
10     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
11     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
12     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
13     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
14     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
15     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
16     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
17     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
18     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
19     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
20     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
21     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
22     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
23     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
24     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
25     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
26     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
27     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
28     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
29     U.S. Environmental Protection Agency; U.S. Cen...   2014-2016
...                                                  ...         ...
37708           CDC, Water Fluoridation Reporting System        2014
37709           CDC, Water Fluoridation Reporting System        2014
37710           CDC, Water Fluoridation Reporting System        2014
37711           CDC, Water Fluoridation Reporting System        2014
37712           CDC, Water Fluoridation Reporting System        2014
37713           CDC, Water Fluoridation Reporting System        2014
37714           CDC, Water Fluoridation Reporting System        2014
37715           CDC, Water Fluoridation Reporting System        2014
37716           CDC, Water Fluoridation Reporting System        2014
37717           CDC, Water Fluoridation Reporting System        2014
37718           CDC, Water Fluoridation Reporting System        2014
37719           CDC, Water Fluoridation Reporting System        2014
37720           CDC, Water Fluoridation Reporting System        2014
37721           CDC, Water Fluoridation Reporting System        2014
37722           CDC, Water Fluoridation Reporting System        2014
37723           CDC, Water Fluoridation Reporting System        2014
37724           CDC, Water Fluoridation Reporting System        2014
37725           CDC, Water Fluoridation Reporting System        2014
37726           CDC, Water Fluoridation Reporting System        2014
37727           CDC, Water Fluoridation Reporting System        2014
37728           CDC, Water Fluoridation Reporting System        2014
37729           CDC, Water Fluoridation Reporting System        2014
37730           CDC, Water Fluoridation Reporting System        2014
37731           CDC, Water Fluoridation Reporting System        2014
37732           CDC, Water Fluoridation Reporting System        2014
37733           CDC, Water Fluoridation Reporting System        2014
37734           CDC, Water Fluoridation Reporting System        2014
37735           CDC, Water Fluoridation Reporting System        2014
37736           CDC, Water Fluoridation Reporting System        2014
37737           CDC, Water Fluoridation Reporting System        2014

[37738 rows x 11 columns]

In [3]:
df2017 = pd.DataFrame(file)
df2017.head()

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
0,2017,2017 Annual,Air Pollution,Alaska,36.0,8.7,0.06,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2014-2016
1,2017,2017 Annual,Air Pollution,Alabama,39.0,8.9,0.19,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2014-2016
2,2017,2017 Annual,Air Pollution,Arkansas,16.0,7.2,-0.90,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2014-2016
3,2017,2017 Annual,Air Pollution,Arizona,46.0,9.7,0.71,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2014-2016
4,2017,2017 Annual,Air Pollution,California,50.0,11.7,2.00,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2014-2016

In [4]:
df2017.count()

Edition         37738
Report Type     37738
Measure Name    37738
State Name      37738
Rank            31308
Value           32122
Score           31156
Lower CI        34409
Upper CI        34409
Source          37738
Source Year     37322
dtype: int64

In [5]:
df2017['Measure Name'].unique()

array(['Air Pollution', 'All Determinants', 'All Outcomes', 'Behaviors',
       'Binge Drinking', 'Binge Drinking - $25-$49,999',
       'Binge Drinking - $50-$74,999', 'Binge Drinking - $75,000 or More',
       'Binge Drinking - Ages 18-44', 'Binge Drinking - Ages 45-64',
       'Binge Drinking - Ages 65+',
       'Binge Drinking - American Indian/Alaskan Native',
       'Binge Drinking - Asian', 'Binge Drinking - Black',
       'Binge Drinking - College Grad', 'Binge Drinking - Female',
       'Binge Drinking - Hawaiian/Pacific Islander',
       'Binge Drinking - High School Grad', 'Binge Drinking - Hispanic',
       'Binge Drinking - Less Than $25,000',
       'Binge Drinking - Less Than High School', 'Binge Drinking - Male',
       'Binge Drinking - Multiracial', 'Binge Drinking - Other Race',
       'Binge Drinking - Rural', 'Binge Drinking - Some College',
       'Binge Drinking - Suburban', 'Binge Drinking - Urban',
       'Binge Drinking - White', 'Cancer Deaths',
       'Cancer Deaths - American Indian/Alaska Native',
       'Cancer Deaths - Asian/Pacific Islander',
       'Cancer Deaths - Black/African American',
       'Cancer Deaths - Crude Rate', 'Cancer Deaths - Female',
       'Cancer Deaths - Hispanic/Latino', 'Cancer Deaths - Male',
       'Cancer Deaths - Standard Age Adjustment', 'Cancer Deaths - White',
       'Cardiovascular Deaths',
       'Cardiovascular Deaths - American Indian/Alaska Native',
       'Cardiovascular Deaths - Asian/Pacific Islander',
       'Cardiovascular Deaths - Black/African American',
       'Cardiovascular Deaths - Crude Rate',
       'Cardiovascular Deaths - Female',
       'Cardiovascular Deaths - Hispanic/Latino',
       'Cardiovascular Deaths - Male',
       'Cardiovascular Deaths - Standard Age Adjustment',
       'Cardiovascular Deaths - White', 'Children in Poverty',
       'Chlamydia', 'Chlamydia - American Indian/Alaska Native',
       'Chlamydia - Asian', 'Chlamydia - Black/African American',
       'Chlamydia - Female', 'Chlamydia - Hispanic/Latino',
       'Chlamydia - Male', 'Chlamydia - Multiracial',
       'Chlamydia - Native Hawaiian/ PI', 'Chlamydia - White',
       'Cholesterol Check', 'Cholesterol Check - $25-$49,999',
       'Cholesterol Check - $50-$74,999',
       'Cholesterol Check - $75,000 or More',
       'Cholesterol Check - Ages 18-44', 'Cholesterol Check - Ages 45-64',
       'Cholesterol Check - Ages 65+',
       'Cholesterol Check - American Indian/Alaskan Native',
       'Cholesterol Check - Asian', 'Cholesterol Check - Black',
       'Cholesterol Check - College Grad', 'Cholesterol Check - Female',
       'Cholesterol Check - Hawaiian/Pacific Islander',
       'Cholesterol Check - High School Grad',
       'Cholesterol Check - Hispanic',
       'Cholesterol Check - Less Than $25,000',
       'Cholesterol Check - Less Than High School',
       'Cholesterol Check - Male', 'Cholesterol Check - Rural',
       'Cholesterol Check - Some College', 'Cholesterol Check - Suburban',
       'Cholesterol Check - Urban', 'Cholesterol Check - White',
       'Chronic Drinking', 'Chronic Drinking - $25-$49,999',
       'Chronic Drinking - $50-$74,999',
       'Chronic Drinking - $75,000 or More',
       'Chronic Drinking - Ages 18-44', 'Chronic Drinking - Ages 45-64',
       'Chronic Drinking - Ages 65+',
       'Chronic Drinking - American Indian/Alaskan Native',
       'Chronic Drinking - Asian', 'Chronic Drinking - Black',
       'Chronic Drinking - College Grad', 'Chronic Drinking - Female',
       'Chronic Drinking - Hawaiian/Pacific Islander',
       'Chronic Drinking - High School Grad',
       'Chronic Drinking - Hispanic',
       'Chronic Drinking - Less Than $25,000',
       'Chronic Drinking - Less Than High School',
       'Chronic Drinking - Male', 'Chronic Drinking - Multiracial',
       'Chronic Drinking - Other Race', 'Chronic Drinking - Rural',
       'Chronic Drinking - Some College', 'Chronic Drinking - Suburban',
       'Chronic Drinking - Urban', 'Chronic Drinking - White',
       'Clinical Care', 'Colorectal Cancer Screening',
       'Colorectal Cancer Screening - $25-$49,999',
       'Colorectal Cancer Screening - $50-$74,999',
       'Colorectal Cancer Screening - $75,000 or More',
       'Colorectal Cancer Screening - American Indian/Alaskan Native',
       'Colorectal Cancer Screening - Asian',
       'Colorectal Cancer Screening - Black',
       'Colorectal Cancer Screening - College Grad',
       'Colorectal Cancer Screening - Female',
       'Colorectal Cancer Screening - Hawaiian/Pacific Islander',
       'Colorectal Cancer Screening - High School Grad',
       'Colorectal Cancer Screening - Hispanic',
       'Colorectal Cancer Screening - Less Than $25,000',
       'Colorectal Cancer Screening - Less Than High School',
       'Colorectal Cancer Screening - Male',
       'Colorectal Cancer Screening - Multiracial',
       'Colorectal Cancer Screening - Other Race',
       'Colorectal Cancer Screening - Rural',
       'Colorectal Cancer Screening - Some College',
       'Colorectal Cancer Screening - Suburban',
       'Colorectal Cancer Screening - Urban',
       'Colorectal Cancer Screening - White', 'Community & Environment',
       'Dedicated HC Provider - $25-$49,999',
       'Dedicated HC Provider - $50-$74,999',
       'Dedicated HC Provider - $75,000 or More',
       'Dedicated HC Provider - 18-44', 'Dedicated HC Provider - 45-64',
       'Dedicated HC Provider - 65+',
       'Dedicated HC Provider - American Indian/Alaskan Native',
       'Dedicated HC Provider - Asian', 'Dedicated HC Provider - Black',
       'Dedicated HC Provider - College Grad',
       'Dedicated HC Provider - Female',
       'Dedicated HC Provider - Hawaiian/Pacific Islander',
       'Dedicated HC Provider - High School Grad',
       'Dedicated HC Provider - Hispanic',
       'Dedicated HC Provider - Less Than $25,000',
       'Dedicated HC Provider - Less Than High School',
       'Dedicated HC Provider - Male',
       'Dedicated HC Provider - Multiracial',
       'Dedicated HC Provider - Other Race',
       'Dedicated HC Provider - Rural',
       'Dedicated HC Provider - Some College',
       'Dedicated HC Provider - Suburban',
       'Dedicated HC Provider - Urban', 'Dedicated HC Provider - White',
       'Dedicated Health Care Provider', 'Dental Visit - $25-$49,999',
       'Dental Visit - $50-$74,999', 'Dental Visit - $75,000 or More',
       'Dental Visit - Ages 18-44', 'Dental Visit - Ages 45-64',
       'Dental Visit - Ages 65+',
       'Dental Visit - American Indian/Alaskan Native',
       'Dental Visit - Asian', 'Dental Visit - Black',
       'Dental Visit - College Grad', 'Dental Visit - Female',
       'Dental Visit - Hawaiian/Pacific Islander',
       'Dental Visit - High School Grad', 'Dental Visit - Hispanic',
       'Dental Visit - Less Than $25,000',
       'Dental Visit - Less Than High School', 'Dental Visit - Male',
       'Dental Visit - Multiracial', 'Dental Visit - Other Race',
       'Dental Visit - Rural', 'Dental Visit - Some College',
       'Dental Visit - Suburban', 'Dental Visit - Urban',
       'Dental Visit - White', 'Dental Visit, Annual', 'Dentists',
       'Diabetes', 'Diabetes - $25-$49,999', 'Diabetes - $50-$74,999',
       'Diabetes - $75,000 or More', 'Diabetes - Ages 18-44',
       'Diabetes - Ages 45-64', 'Diabetes - Ages 65+',
       'Diabetes - American Indian/Alaskan Native', 'Diabetes - Asian',
       'Diabetes - Black', 'Diabetes - College Grad', 'Diabetes - Female',
       'Diabetes - Hawaiian/Pacific Islander',
       'Diabetes - High School Grad', 'Diabetes - Hispanic',
       'Diabetes - Less Than $25,000', 'Diabetes - Less Than High School',
       'Diabetes - Male', 'Diabetes - Multiracial',
       'Diabetes - Other Race', 'Diabetes - Rural',
       'Diabetes - Some College', 'Diabetes - Suburban',
       'Diabetes - Urban', 'Diabetes - White', 'Disconnected Youth',
       'Disparity in Health Status', 'Drug Deaths',
       'Drug Deaths - American Indian/Alaska Native',
       'Drug Deaths - Asian/Pacific Islander',
       'Drug Deaths - Black/African American', 'Drug Deaths - Female',
       'Drug Deaths - Hispanic/Latino', 'Drug Deaths - Male',
       'Drug Deaths - White', 'Excessive Drinking',
       'Excessive Drinking - $25-$49,999',
       'Excessive Drinking - $50-$74,999',
       'Excessive Drinking - $75,000 or More',
       'Excessive Drinking - Ages 18-44',
       'Excessive Drinking - Ages 45-64', 'Excessive Drinking - Ages 65+',
       'Excessive Drinking - American Indian/Alaskan Native',
       'Excessive Drinking - Asian', 'Excessive Drinking - Black',
       'Excessive Drinking - College Grad', 'Excessive Drinking - Female',
       'Excessive Drinking - Hawaiian/Pacific Islander',
       'Excessive Drinking - High School Grad',
       'Excessive Drinking - Hispanic',
       'Excessive Drinking - Less Than $25,000',
       'Excessive Drinking - Less Than High School',
       'Excessive Drinking - Male', 'Excessive Drinking - Multiracial',
       'Excessive Drinking - Other Race', 'Excessive Drinking - Rural',
       'Excessive Drinking - Some College',
       'Excessive Drinking - Suburban', 'Excessive Drinking - Urban',
       'Excessive Drinking - White', 'Frequent Mental Distress',
       'Frequent Mental Distress - $25-$49,999',
       'Frequent Mental Distress - $50-$74,999',
       'Frequent Mental Distress - $75,000 or More',
       'Frequent Mental Distress - Ages 18-44',
       'Frequent Mental Distress - Ages 45-64',
       'Frequent Mental Distress - Ages 65+',
       'Frequent Mental Distress - American Indian/Alaskan Native',
       'Frequent Mental Distress - Asian',
       'Frequent Mental Distress - Black',
       'Frequent Mental Distress - College Grad',
       'Frequent Mental Distress - Female',
       'Frequent Mental Distress - Hawaiian/Pacific Islander',
       'Frequent Mental Distress - High School Grad',
       'Frequent Mental Distress - Hispanic',
       'Frequent Mental Distress - Less Than $25,000',
       'Frequent Mental Distress - Less Than High School',
       'Frequent Mental Distress - Male',
       'Frequent Mental Distress - Multiracial',
       'Frequent Mental Distress - Other Race',
       'Frequent Mental Distress - Rural',
       'Frequent Mental Distress - Some College',
       'Frequent Mental Distress - Suburban',
       'Frequent Mental Distress - Urban',
       'Frequent Mental Distress - White', 'Frequent Physical Distress',
       'Frequent Physical Distress - $25-$49,999',
       'Frequent Physical Distress - $50-$74,999',
       'Frequent Physical Distress - $75,000 or More',
       'Frequent Physical Distress - Ages 18-44',
       'Frequent Physical Distress - Ages 45-64',
       'Frequent Physical Distress - Ages 65+',
       'Frequent Physical Distress - American Indian/Alaskan Native',
       'Frequent Physical Distress - Asian',
       'Frequent Physical Distress - Black',
       'Frequent Physical Distress - College Grad',
       'Frequent Physical Distress - Female',
       'Frequent Physical Distress - Hawaiian/Pacific Islander',
       'Frequent Physical Distress - High School Grad',
       'Frequent Physical Distress - Hispanic',
       'Frequent Physical Distress - Less Than $25,000',
       'Frequent Physical Distress - Less Than High School',
       'Frequent Physical Distress - Male',
       'Frequent Physical Distress - Multiracial',
       'Frequent Physical Distress - Other Race',
       'Frequent Physical Distress - Rural',
       'Frequent Physical Distress - Some College',
       'Frequent Physical Distress - Suburban',
       'Frequent Physical Distress - Urban',
       'Frequent Physical Distress - White', 'Fruits', 'Heart Attack',
       'Heart Attack - $25-$49,999', 'Heart Attack - $50-$74,999',
       'Heart Attack - $75,000 or More', 'Heart Attack - Ages 18-44',
       'Heart Attack - Ages 45-64', 'Heart Attack - Ages 65+',
       'Heart Attack - American Indian/Alaskan Native',
       'Heart Attack - Asian', 'Heart Attack - Black',
       'Heart Attack - College Grad', 'Heart Attack - Female',
       'Heart Attack - Hawaiian/Pacific Islander',
       'Heart Attack - High School Grad', 'Heart Attack - Hispanic',
       'Heart Attack - Less Than $25,000',
       'Heart Attack - Less Than High School', 'Heart Attack - Male',
       'Heart Attack - Multiracial', 'Heart Attack - Other Race',
       'Heart Attack - Rural', 'Heart Attack - Some College',
       'Heart Attack - Suburban', 'Heart Attack - Urban',
       'Heart Attack - White', 'Heart Disease',
       'Heart Disease - $25-$49,999', 'Heart Disease - $50-$74,999',
       'Heart Disease - $75,000 or More', 'Heart Disease - Ages 18-44',
       'Heart Disease - Ages 45-64', 'Heart Disease - Ages 65+',
       'Heart Disease - American Indian/Alaskan Native',
       'Heart Disease - Asian', 'Heart Disease - Black',
       'Heart Disease - College Grad', 'Heart Disease - Female',
       'Heart Disease - Hawaiian/Pacific Islander',
       'Heart Disease - High School Grad', 'Heart Disease - Hispanic',
       'Heart Disease - Less Than $25,000',
       'Heart Disease - Less Than High School', 'Heart Disease - Male',
       'Heart Disease - Multiracial', 'Heart Disease - Other Race',
       'Heart Disease - Rural', 'Heart Disease - Some College',
       'Heart Disease - Suburban', 'Heart Disease - Urban',
       'Heart Disease - White', 'High Blood Pressure',
       'High Blood Pressure - $25-$49,999',
       'High Blood Pressure - $50-$74,999',
       'High Blood Pressure - $75,000 or More',
       'High Blood Pressure - Ages 18-44',
       'High Blood Pressure - Ages 45-64',
       'High Blood Pressure - Ages 65+',
       'High Blood Pressure - American Indian/Alaskan Native',
       'High Blood Pressure - Asian', 'High Blood Pressure - Black',
       'High Blood Pressure - College Grad',
       'High Blood Pressure - Female',
       'High Blood Pressure - Hawaiian/Pacific Islander',
       'High Blood Pressure - High School Grad',
       'High Blood Pressure - Hispanic',
       'High Blood Pressure - Less Than $25,000',
       'High Blood Pressure - Less Than High School',
       'High Blood Pressure - Male', 'High Blood Pressure - Rural',
       'High Blood Pressure - Some College',
       'High Blood Pressure - Suburban', 'High Blood Pressure - Urban',
       'High Blood Pressure - White', 'High Cholesterol',
       'High Health Status', 'High Health Status - $25-$49,999',
       'High Health Status - $50-$74,999',
       'High Health Status - $75,000 or More',
       'High Health Status - Ages 18-44',
       'High Health Status - Ages 45-64', 'High Health Status - Ages 65+',
       'High Health Status - American Indian/Alaskan Native',
       'High Health Status - Asian', 'High Health Status - Black',
       'High Health Status - College Grad', 'High Health Status - Female',
       'High Health Status - Hawaiian/Pacific Islander',
       'High Health Status - High School Grad',
       'High Health Status - Hispanic',
       'High Health Status - Less Than $25,000',
       'High Health Status - Less Than High School',
       'High Health Status - Male', 'High Health Status - Multiracial',
       'High Health Status - Other Race', 'High Health Status - Rural',
       'High Health Status - Some College',
       'High Health Status - Suburban', 'High Health Status - Urban',
       'High Health Status - White', 'High School Graduation',
       'High School Graduation - American Indian/Alaska Native',
       'High School Graduation - Asian/Pacific Islander',
       'High School Graduation - Black',
       'High School Graduation - Hispanic',
       'High School Graduation - White', 'HPV Immunization Females',
       'HPV Immunization Females - Above Poverty',
       'HPV Immunization Females - Below Poverty',
       'HPV Immunization Females - Black',
       'HPV Immunization Females - Hispanic',
       'HPV Immunization Females - White', 'HPV Immunization Males',
       'HPV Immunization Males - Above Poverty',
       'HPV Immunization Males - Below Poverty',
       'HPV Immunization Males - Black',
       'HPV Immunization Males - Hispanic',
       'HPV Immunization Males - White', 'Immunization HPV Females',
       'Immunization HPV Males', 'Immunizations - Adolescents',
       'Immunizations - Children', 'Income Disparity Ratio',
       'Income Inequality - Gini Index', 'Infant Mortality',
       'Infectious Disease', 'Injury Deaths',
       'Injury Deaths - Ages 15-24', 'Injury Deaths - Ages 25-34',
       'Injury Deaths - Ages 35-44', 'Injury Deaths - Ages 45-54',
       'Injury Deaths - Ages 5-14', 'Injury Deaths - Ages 55-64',
       'Injury Deaths - Ages 65-74',
       'Injury Deaths - American Indian/Alaskan Native',
       'Injury Deaths - Asian/Pacific Islander', 'Injury Deaths - Black',
       'Injury Deaths - Female', 'Injury Deaths - Hispanic',
       'Injury Deaths - Male', 'Injury Deaths - White',
       'Insufficient Sleep', 'Insufficient Sleep - $25-$49,999',
       'Insufficient Sleep - $50-$74,999',
       'Insufficient Sleep - $75,000 or More',
       'Insufficient Sleep - Ages 18-44',
       'Insufficient Sleep - Ages 45-64', 'Insufficient Sleep - Ages 65+',
       'Insufficient Sleep - American Indian/Alaskan Native',
       'Insufficient Sleep - Asian', 'Insufficient Sleep - Black',
       'Insufficient Sleep - College Grad', 'Insufficient Sleep - Female',
       'Insufficient Sleep - Hawaiian/Pacific Islander',
       'Insufficient Sleep - High School Grad',
       'Insufficient Sleep - Hispanic',
       'Insufficient Sleep - Less Than $25,000',
       'Insufficient Sleep - Less Than High School',
       'Insufficient Sleep - Male', 'Insufficient Sleep - Multiracial',
       'Insufficient Sleep - Other Race', 'Insufficient Sleep - Rural',
       'Insufficient Sleep - Some College',
       'Insufficient Sleep - Suburban', 'Insufficient Sleep - Urban',
       'Insufficient Sleep - White', 'Low Birthweight',
       'Low Birthweight - Black/African American',
       'Low Birthweight - College Graduate',
       'Low Birthweight - High School Graduate',
       'Low Birthweight - Hispanic',
       'Low Birthweight - Less Than High School',
       'Low Birthweight - Mother Ages 15-19',
       'Low Birthweight - Mother Ages 20-24',
       'Low Birthweight - Mother Ages 25-29',
       'Low Birthweight - Mother Ages 30-34',
       'Low Birthweight - Mother Ages 35-39',
       'Low Birthweight - Mother Ages 40-44',
       'Low Birthweight - Some College', 'Low Birthweight - White',
       'Median Household Income', 'Meningococcal Immunizations',
       'Meningococcal Immunizations - Above Poverty',
       'Meningococcal Immunizations - Below Poverty',
       'Meningococcal Immunizations - Black',
       'Meningococcal Immunizations - Hispanic',
       'Meningococcal Immunizations - White', 'Mental Health Providers',
       'Neighborhood Amenities', 'Obesity', 'Obesity - $25-$49,999',
       'Obesity - $50-$74,999', 'Obesity - $75,000 or More',
       'Obesity - Ages 18-44', 'Obesity - Ages 45-64',
       'Obesity - Ages 65+', 'Obesity - American Indian/Alaskan Native',
       'Obesity - Asian', 'Obesity - Black', 'Obesity - College Grad',
       'Obesity - Female', 'Obesity - Hawaiian/Pacific Islander',
       'Obesity - High School Grad', 'Obesity - Hispanic',
       'Obesity - Less Than $25,000', 'Obesity - Less Than High School',
       'Obesity - Male', 'Obesity - Multiracial', 'Obesity - Other Race',
       'Obesity - Rural', 'Obesity - Some College', 'Obesity - Suburban',
       'Obesity - Urban', 'Obesity - White', 'Occupational Fatalities',
       'Overall', 'Personal Income, Per Capita ', 'Pertussis',
       'Physical Inactivity', 'Physical Inactivity - $25-$49,999',
       'Physical Inactivity - $50-$74,999',
       'Physical Inactivity - $75,000 or More',
       'Physical Inactivity - Ages 18-44',

In [6]:
#'Below poverty threshold','Cancer Deaths','Cardiovascular Deaths','Cholesterol Check','Diabetes','Drug Deaths',

In [7]:
Underemployment_Rate=df2017[df2017['Measure Name']=='Underemployment Rate']

In [8]:
Underemployment_Rate.head()

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
36802,2017,2017 Annual,Underemployment Rate,Alaska,50.0,12.8,1.868,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36803,2017,2017 Annual,Underemployment Rate,Alabama,38.0,10.4,0.467,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36804,2017,2017 Annual,Underemployment Rate,United States,NaN,9.6,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36805,2017,2017 Annual,Underemployment Rate,Arkansas,8.0,7.5,-1.226,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36806,2017,2017 Annual,Underemployment Rate,Arizona,42.0,10.8,0.700,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016

In [9]:
Underemployment_Rate.isnull().any()

Edition         False
Report Type     False
Measure Name    False
State Name      False
Rank             True
Value           False
Score            True
Lower CI         True
Upper CI         True
Source          False
Source Year     False
dtype: bool

In [10]:
Underemployment_Rate.loc[Underemployment_Rate.isnull().any(axis=1)]

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
36802,2017,2017 Annual,Underemployment Rate,Alaska,50.0,12.8,1.868,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36803,2017,2017 Annual,Underemployment Rate,Alabama,38.0,10.4,0.467,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36804,2017,2017 Annual,Underemployment Rate,United States,NaN,9.6,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36805,2017,2017 Annual,Underemployment Rate,Arkansas,8.0,7.5,-1.226,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36806,2017,2017 Annual,Underemployment Rate,Arizona,42.0,10.8,0.700,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36807,2017,2017 Annual,Underemployment Rate,California,47.0,11.3,0.992,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36808,2017,2017 Annual,Underemployment Rate,Colorado,7.0,7.3,-1.342,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36809,2017,2017 Annual,Underemployment Rate,Connecticut,42.0,10.8,0.700,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36810,2017,2017 Annual,Underemployment Rate,District of Columbia,NaN,9.5,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36811,2017,2017 Annual,Underemployment Rate,Delaware,18.0,8.3,-0.759,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36812,2017,2017 Annual,Underemployment Rate,Florida,34.0,10.3,0.409,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36813,2017,2017 Annual,Underemployment Rate,Georgia,39.0,10.5,0.525,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36814,2017,2017 Annual,Underemployment Rate,Hawaii,8.0,7.5,-1.226,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36815,2017,2017 Annual,Underemployment Rate,Iowa,6.0,7.2,-1.401,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36816,2017,2017 Annual,Underemployment Rate,Idaho,12.0,7.8,-1.051,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36817,2017,2017 Annual,Underemployment Rate,Illinois,45.0,11.0,0.817,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36818,2017,2017 Annual,Underemployment Rate,Indiana,18.0,8.3,-0.759,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36819,2017,2017 Annual,Underemployment Rate,Kansas,17.0,8.2,-0.817,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36820,2017,2017 Annual,Underemployment Rate,Kentucky,28.0,9.7,0.058,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36821,2017,2017 Annual,Underemployment Rate,Louisiana,41.0,10.7,0.642,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36822,2017,2017 Annual,Underemployment Rate,Massachusetts,15.0,8.1,-0.876,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36823,2017,2017 Annual,Underemployment Rate,Maryland,15.0,8.1,-0.876,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36824,2017,2017 Annual,Underemployment Rate,Maine,22.0,8.7,-0.525,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36825,2017,2017 Annual,Underemployment Rate,Michigan,34.0,10.3,0.409,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36826,2017,2017 Annual,Underemployment Rate,Minnesota,11.0,7.7,-1.109,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36827,2017,2017 Annual,Underemployment Rate,Missouri,12.0,7.8,-1.051,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36828,2017,2017 Annual,Underemployment Rate,Mississippi,44.0,10.9,0.759,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36829,2017,2017 Annual,Underemployment Rate,Montana,20.0,8.5,-0.642,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36830,2017,2017 Annual,Underemployment Rate,North Carolina,25.0,9.4,-0.117,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36831,2017,2017 Annual,Underemployment Rate,North Dakota,2.0,6.2,-1.985,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36832,2017,2017 Annual,Underemployment Rate,Nebraska,2.0,6.2,-1.985,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36833,2017,2017 Annual,Underemployment Rate,New Hampshire,4.0,6.4,-1.868,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36834,2017,2017 Annual,Underemployment Rate,New Jersey,28.0,9.7,0.058,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36835,2017,2017 Annual,Underemployment Rate,New Mexico,49.0,12.6,1.751,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36836,2017,2017 Annual,Underemployment Rate,Nevada,48.0,12.2,1.518,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36837,2017,2017 Annual,Underemployment Rate,New York,25.0,9.4,-0.117,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36838,2017,2017 Annual,Underemployment Rate,Ohio,28.0,9.7,0.058,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36839,2017,2017 Annual,Underemployment Rate,Oklahoma,24.0,9.2,-0.233,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36840,2017,2017 Annual,Underemployment Rate,Oregon,34.0,10.3,0.409,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36841,2017,2017 Annual,Underemployment Rate,Pennsylvania,40.0,10.6,0.584,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36842,2017,2017 Annual,Underemployment Rate,Rhode Island,32.0,10.1,0.292,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36843,2017,2017 Annual,Underemployment Rate,South Carolina,28.0,9.7,0.058,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36844,2017,2017 Annual,Underemployment Rate,South Dakota,1.0,5.2,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36845,2017,2017 Annual,Underemployment Rate,Tennessee,25.0,9.4,-0.117,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36846,2017,2017 Annual,Underemployment Rate,Texas,21.0,8.6,-0.584,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36847,2017,2017 Annual,Underemployment Rate,Utah,8.0,7.5,-1.226,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36848,2017,2017 Annual,Underemployment Rate,Virginia,23.0,9.1,-0.292,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36849,2017,2017 Annual,Underemployment Rate,Vermont,5.0,7.1,-1.459,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36850,2017,2017 Annual,Underemployment Rate,Washington,34.0,10.3,0.409,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36851,2017,2017 Annual,Underemployment Rate,Wisconsin,14.0,7.9,-0.992,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36852,2017,2017 Annual,Underemployment Rate,West Virginia,45.0,11.0,0.817,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36853,2017,2017 Annual,Underemployment Rate,Wyoming,32.0,10.1,0.292,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2016

In [11]:
Underemployment_Rate = Underemployment_Rate.fillna(value=0)
Underemployment_Rate

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
36802,2017,2017 Annual,Underemployment Rate,Alaska,50.0,12.8,1.868,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36803,2017,2017 Annual,Underemployment Rate,Alabama,38.0,10.4,0.467,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36804,2017,2017 Annual,Underemployment Rate,United States,0.0,9.6,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36805,2017,2017 Annual,Underemployment Rate,Arkansas,8.0,7.5,-1.226,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36806,2017,2017 Annual,Underemployment Rate,Arizona,42.0,10.8,0.700,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36807,2017,2017 Annual,Underemployment Rate,California,47.0,11.3,0.992,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36808,2017,2017 Annual,Underemployment Rate,Colorado,7.0,7.3,-1.342,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36809,2017,2017 Annual,Underemployment Rate,Connecticut,42.0,10.8,0.700,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36810,2017,2017 Annual,Underemployment Rate,District of Columbia,0.0,9.5,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36811,2017,2017 Annual,Underemployment Rate,Delaware,18.0,8.3,-0.759,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36812,2017,2017 Annual,Underemployment Rate,Florida,34.0,10.3,0.409,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36813,2017,2017 Annual,Underemployment Rate,Georgia,39.0,10.5,0.525,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36814,2017,2017 Annual,Underemployment Rate,Hawaii,8.0,7.5,-1.226,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36815,2017,2017 Annual,Underemployment Rate,Iowa,6.0,7.2,-1.401,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36816,2017,2017 Annual,Underemployment Rate,Idaho,12.0,7.8,-1.051,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36817,2017,2017 Annual,Underemployment Rate,Illinois,45.0,11.0,0.817,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36818,2017,2017 Annual,Underemployment Rate,Indiana,18.0,8.3,-0.759,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36819,2017,2017 Annual,Underemployment Rate,Kansas,17.0,8.2,-0.817,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36820,2017,2017 Annual,Underemployment Rate,Kentucky,28.0,9.7,0.058,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36821,2017,2017 Annual,Underemployment Rate,Louisiana,41.0,10.7,0.642,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36822,2017,2017 Annual,Underemployment Rate,Massachusetts,15.0,8.1,-0.876,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36823,2017,2017 Annual,Underemployment Rate,Maryland,15.0,8.1,-0.876,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36824,2017,2017 Annual,Underemployment Rate,Maine,22.0,8.7,-0.525,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36825,2017,2017 Annual,Underemployment Rate,Michigan,34.0,10.3,0.409,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36826,2017,2017 Annual,Underemployment Rate,Minnesota,11.0,7.7,-1.109,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36827,2017,2017 Annual,Underemployment Rate,Missouri,12.0,7.8,-1.051,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36828,2017,2017 Annual,Underemployment Rate,Mississippi,44.0,10.9,0.759,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36829,2017,2017 Annual,Underemployment Rate,Montana,20.0,8.5,-0.642,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36830,2017,2017 Annual,Underemployment Rate,North Carolina,25.0,9.4,-0.117,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36831,2017,2017 Annual,Underemployment Rate,North Dakota,2.0,6.2,-1.985,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36832,2017,2017 Annual,Underemployment Rate,Nebraska,2.0,6.2,-1.985,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36833,2017,2017 Annual,Underemployment Rate,New Hampshire,4.0,6.4,-1.868,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36834,2017,2017 Annual,Underemployment Rate,New Jersey,28.0,9.7,0.058,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36835,2017,2017 Annual,Underemployment Rate,New Mexico,49.0,12.6,1.751,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36836,2017,2017 Annual,Underemployment Rate,Nevada,48.0,12.2,1.518,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36837,2017,2017 Annual,Underemployment Rate,New York,25.0,9.4,-0.117,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36838,2017,2017 Annual,Underemployment Rate,Ohio,28.0,9.7,0.058,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36839,2017,2017 Annual,Underemployment Rate,Oklahoma,24.0,9.2,-0.233,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36840,2017,2017 Annual,Underemployment Rate,Oregon,34.0,10.3,0.409,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36841,2017,2017 Annual,Underemployment Rate,Pennsylvania,40.0,10.6,0.584,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36842,2017,2017 Annual,Underemployment Rate,Rhode Island,32.0,10.1,0.292,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36843,2017,2017 Annual,Underemployment Rate,South Carolina,28.0,9.7,0.058,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36844,2017,2017 Annual,Underemployment Rate,South Dakota,1.0,5.2,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36845,2017,2017 Annual,Underemployment Rate,Tennessee,25.0,9.4,-0.117,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36846,2017,2017 Annual,Underemployment Rate,Texas,21.0,8.6,-0.584,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36847,2017,2017 Annual,Underemployment Rate,Utah,8.0,7.5,-1.226,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36848,2017,2017 Annual,Underemployment Rate,Virginia,23.0,9.1,-0.292,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36849,2017,2017 Annual,Underemployment Rate,Vermont,5.0,7.1,-1.459,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36850,2017,2017 Annual,Underemployment Rate,Washington,34.0,10.3,0.409,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36851,2017,2017 Annual,Underemployment Rate,Wisconsin,14.0,7.9,-0.992,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36852,2017,2017 Annual,Underemployment Rate,West Virginia,45.0,11.0,0.817,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016
36853,2017,2017 Annual,Underemployment Rate,Wyoming,32.0,10.1,0.292,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2016

In [12]:
Underemployment_Rate.count()

Edition         52
Report Type     52
Measure Name    52
State Name      52
Rank            52
Value           52
Score           52
Lower CI        52
Upper CI        52
Source          52
Source Year     52
dtype: int64

In [13]:
list(Underemployment_Rate.columns.values)

['Edition',
 'Report Type',
 'Measure Name',
 'State Name',
 'Rank',
 'Value',
 'Score',
 'Lower CI',
 'Upper CI',
 'Source',
 'Source Year']

In [14]:
Underemployment_Rate= Underemployment_Rate[["State Name",
                                "Edition", 
                              "Measure Name",
                              "Rank",
                              "Value"]]

In [15]:
Underemployment_Rate.head()

          State Name  Edition          Measure Name  Rank  Value
36802         Alaska     2017  Underemployment Rate  50.0   12.8
36803        Alabama     2017  Underemployment Rate  38.0   10.4
36804  United States     2017  Underemployment Rate   0.0    9.6
36805       Arkansas     2017  Underemployment Rate   8.0    7.5
36806        Arizona     2017  Underemployment Rate  42.0   10.8

In [16]:
Underemployment_Rate.rename(columns = {'Rank' : 'Underemployment_Rate_Rank', 
                             'Value' : 'Underemployment_Rate_Value',
                            'State Name': 'State',
                            'Edition': 'Year'}, 
                  inplace = True)

C:\Users\steph\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [17]:
Underemployment_Rate.head()

,State,Year,Measure Name,Underemployment_Rate_Rank,Underemployment_Rate_Value
36802,Alaska,2017,Underemployment Rate,50.0,12.8
36803,Alabama,2017,Underemployment Rate,38.0,10.4
36804,United States,2017,Underemployment Rate,0.0,9.6
36805,Arkansas,2017,Underemployment Rate,8.0,7.5
36806,Arizona,2017,Underemployment Rate,42.0,10.8

In [18]:
Underemployment_Rate = Underemployment_Rate.drop('Measure Name',axis=1)

In [19]:
Underemployment_Rate.head()

,State,Year,Underemployment_Rate_Rank,Underemployment_Rate_Value
36802,Alaska,2017,50.0,12.8
36803,Alabama,2017,38.0,10.4
36804,United States,2017,0.0,9.6
36805,Arkansas,2017,8.0,7.5
36806,Arizona,2017,42.0,10.8

In [20]:
Underemployment_Rate.to_csv(os.path.join("..","..","Data","Raw","America_Health_Rankings","2017 MidStep","Underemployment_Rate.csv"),index = False)