In [1]:
import pandas as pd
from datetime import datetime
import os
import numpy as np

In [2]:
file = pd.read_csv(os.path.join("..","..","Data","Raw","America_Health_Rankings","2014-Annual.csv"))
print(file)

       Edition  Report Type   Measure Name            State Name Rank  Value  \
0         2014  2014 Annual  Air Pollution               Alabama   36   10.0
1         2014  2014 Annual  Air Pollution                Alaska    1    4.9
2         2014  2014 Annual  Air Pollution               Arizona   35    9.9
3         2014  2014 Annual  Air Pollution              Arkansas   42   10.3
4         2014  2014 Annual  Air Pollution            California   50   13.9
5         2014  2014 Annual  Air Pollution              Colorado    7    6.8
6         2014  2014 Annual  Air Pollution           Connecticut   19    8.7
7         2014  2014 Annual  Air Pollution              Delaware   40   10.2
8         2014  2014 Annual  Air Pollution               Florida   10    7.4
9         2014  2014 Annual  Air Pollution               Georgia   42   10.3
10        2014  2014 Annual  Air Pollution                Hawaii   19    8.7
11        2014  2014 Annual  Air Pollution                 Idaho   44   10.4
12        2014  2014 Annual  Air Pollution              Illinois   47   11.4
13        2014  2014 Annual  Air Pollution               Indiana   48   11.7
14        2014  2014 Annual  Air Pollution                  Iowa   32    9.6
15        2014  2014 Annual  Air Pollution                Kansas   22    8.8
16        2014  2014 Annual  Air Pollution              Kentucky   44   10.4
17        2014  2014 Annual  Air Pollution             Louisiana   26    9.2
18        2014  2014 Annual  Air Pollution                 Maine   12    7.6
19        2014  2014 Annual  Air Pollution              Maryland   36   10.0
20        2014  2014 Annual  Air Pollution         Massachusetts   13    7.7
21        2014  2014 Annual  Air Pollution              Michigan   22    8.8
22        2014  2014 Annual  Air Pollution             Minnesota   14    8.0
23        2014  2014 Annual  Air Pollution           Mississippi   27    9.3
24        2014  2014 Annual  Air Pollution              Missouri   36   10.0
25        2014  2014 Annual  Air Pollution               Montana    4    6.3
26        2014  2014 Annual  Air Pollution              Nebraska   14    8.0
27        2014  2014 Annual  Air Pollution                Nevada   27    9.3
28        2014  2014 Annual  Air Pollution         New Hampshire   11    7.5
29        2014  2014 Annual  Air Pollution            New Jersey   24    9.0
...        ...          ...            ...                   ...  ...    ...
28476     2014  2014 Annual  Youth Smoking             Minnesota  NaN    NaN
28477     2014  2014 Annual  Youth Smoking           Mississippi  NaN   17.2
28478     2014  2014 Annual  Youth Smoking              Missouri  NaN   14.9
28479     2014  2014 Annual  Youth Smoking               Montana  NaN   15.2
28480     2014  2014 Annual  Youth Smoking              Nebraska  NaN   10.9
28481     2014  2014 Annual  Youth Smoking                Nevada  NaN   10.3
28482     2014  2014 Annual  Youth Smoking         New Hampshire  NaN   13.8
28483     2014  2014 Annual  Youth Smoking            New Jersey  NaN   12.9
28484     2014  2014 Annual  Youth Smoking            New Mexico  NaN   14.4
28485     2014  2014 Annual  Youth Smoking              New York  NaN   10.6
28486     2014  2014 Annual  Youth Smoking        North Carolina  NaN   15.0
28487     2014  2014 Annual  Youth Smoking          North Dakota  NaN   19.0
28488     2014  2014 Annual  Youth Smoking                  Ohio  NaN   15.1
28489     2014  2014 Annual  Youth Smoking              Oklahoma  NaN   18.5
28490     2014  2014 Annual  Youth Smoking                Oregon  NaN    NaN
28491     2014  2014 Annual  Youth Smoking          Pennsylvania  NaN    NaN
28492     2014  2014 Annual  Youth Smoking          Rhode Island  NaN    8.0
28493     2014  2014 Annual  Youth Smoking        South Carolina  NaN   16.0
28494     2014  2014 Annual  Youth Smoking          South Dakota  NaN   16.5
28495     2014  2014 Annual  Youth Smoking             Tennessee  NaN   15.4
28496     2014  2014 Annual  Youth Smoking                 Texas  NaN   14.1
28497     2014  2014 Annual  Youth Smoking                  Utah  NaN    4.4
28498     2014  2014 Annual  Youth Smoking               Vermont  NaN    NaN
28499     2014  2014 Annual  Youth Smoking              Virginia  NaN   11.1
28500     2014  2014 Annual  Youth Smoking            Washington  NaN    NaN
28501     2014  2014 Annual  Youth Smoking         West Virginia  NaN   19.6
28502     2014  2014 Annual  Youth Smoking             Wisconsin  NaN   11.8
28503     2014  2014 Annual  Youth Smoking               Wyoming  NaN   17.4
28504     2014  2014 Annual  Youth Smoking         United States  NaN   15.7
28505     2014  2014 Annual  Youth Smoking  District of Columbia  NaN    NaN

       Score  Lower CI  Upper CI  \
0       0.06       NaN       NaN
1      -2.00       NaN       NaN
2       0.00       NaN       NaN
3       0.22       NaN       NaN
4       2.00       NaN       NaN
5      -1.73       NaN       NaN
6      -0.67       NaN       NaN
7       0.17       NaN       NaN
8      -1.40       NaN       NaN
9       0.22       NaN       NaN
10     -0.67       NaN       NaN
11      0.28       NaN       NaN
12      0.84       NaN       NaN
13      1.01       NaN       NaN
14     -0.17       NaN       NaN
15     -0.61       NaN       NaN
16      0.28       NaN       NaN
17     -0.39       NaN       NaN
18     -1.29       NaN       NaN
19      0.06       NaN       NaN
20     -1.23       NaN       NaN
21     -0.61       NaN       NaN
22     -1.06       NaN       NaN
23     -0.34       NaN       NaN
24      0.06       NaN       NaN
25     -2.00       NaN       NaN
26     -1.06       NaN       NaN
27     -0.34       NaN       NaN
28     -1.34       NaN       NaN
29     -0.50       NaN       NaN
...      ...       ...       ...
28476    NaN       NaN       NaN
28477    NaN      20.4      14.5
28478    NaN      17.2      12.9
28479    NaN      17.2      13.4
28480    NaN      12.9       9.1
28481    NaN      13.2       8.1
28482    NaN      16.4      11.6
28483    NaN      15.3      10.8
28484    NaN      17.0      12.2
28485    NaN      12.2       9.3
28486    NaN      17.3      12.8
28487    NaN      21.7      16.6
28488    NaN      19.6      11.5
28489    NaN      22.0      15.5
28490    NaN       NaN       NaN
28491    NaN       NaN       NaN
28492    NaN      11.0       5.8
28493    NaN      19.0      13.3
28494    NaN      21.4      12.5
28495    NaN      18.3      13.0
28496    NaN      16.8      11.9
28497    NaN       5.9       3.2
28498    NaN       NaN       NaN
28499    NaN      12.7       9.6
28500    NaN       NaN       NaN
28501    NaN      22.7      16.8
28502    NaN      14.1       9.9
28503    NaN      20.4      14.7
28504    NaN      18.1      13.5
28505    NaN       NaN       NaN

                                                  Source Source Year
0      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
1      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
2      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
3      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
4      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
5      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
6      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
7      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
8      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
9      U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
10     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
11     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
12     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
13     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
14     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
15     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
16     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
17     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
18     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
19     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
20     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
21     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
22     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
23     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
24     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
25     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
26     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
27     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
28     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
29     U.S. Environmental Protection Agency; U.S. Cen...   2011-2013
...                                                  ...         ...
28476     CDC, Youth Behavioral Risk Surveillance System        2013
28477     CDC, Youth Behavioral Risk Surveillance System        2013
28478     CDC, Youth Behavioral Risk Surveillance System        2013
28479     CDC, Youth Behavioral Risk Surveillance System        2013
28480     CDC, Youth Behavioral Risk Surveillance System        2013
28481     CDC, Youth Behavioral Risk Surveillance System        2013
28482     CDC, Youth Behavioral Risk Surveillance System        2013
28483     CDC, Youth Behavioral Risk Surveillance System        2013
28484     CDC, Youth Behavioral Risk Surveillance System        2013
28485     CDC, Youth Behavioral Risk Surveillance System        2013
28486     CDC, Youth Behavioral Risk Surveillance System        2013
28487     CDC, Youth Behavioral Risk Surveillance System        2013
28488     CDC, Youth Behavioral Risk Surveillance System        2013
28489     CDC, Youth Behavioral Risk Surveillance System        2013
28490     CDC, Youth Behavioral Risk Surveillance System        2013
28491     CDC, Youth Behavioral Risk Surveillance System        2013
28492     CDC, Youth Behavioral Risk Surveillance System        2013
28493     CDC, Youth Behavioral Risk Surveillance System        2013
28494     CDC, Youth Behavioral Risk Surveillance System        2013
28495     CDC, Youth Behavioral Risk Surveillance System        2013
28496     CDC, Youth Behavioral Risk Surveillance System        2013
28497     CDC, Youth Behavioral Risk Surveillance System        2013
28498     CDC, Youth Behavioral Risk Surveillance System        2013
28499     CDC, Youth Behavioral Risk Surveillance System        2013
28500     CDC, Youth Behavioral Risk Surveillance System        2013
28501     CDC, Youth Behavioral Risk Surveillance System        2013
28502     CDC, Youth Behavioral Risk Surveillance System        2013
28503     CDC, Youth Behavioral Risk Surveillance System        2013
28504     CDC, Youth Behavioral Risk Surveillance System        2013
28505     CDC, Youth Behavioral Risk Surveillance System        2013

[28506 rows x 11 columns]

In [3]:
df2014 = pd.DataFrame(file)
df2014.head()

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
0,2014,2014 Annual,Air Pollution,Alabama,36,10.0,0.06,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2011-2013
1,2014,2014 Annual,Air Pollution,Alaska,1,4.9,-2.00,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2011-2013
2,2014,2014 Annual,Air Pollution,Arizona,35,9.9,0.00,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2011-2013
3,2014,2014 Annual,Air Pollution,Arkansas,42,10.3,0.22,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2011-2013
4,2014,2014 Annual,Air Pollution,California,50,13.9,2.00,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2011-2013

In [4]:
df2014.count()

Edition         28506
Report Type     28495
Measure Name    28495
State Name      28495
Rank            20768
Value           26043
Score           20511
Lower CI        23475
Upper CI        23475
Source          28484
Source Year     27756
dtype: int64

In [5]:
df2014['Measure Name'].unique()

array(['Air Pollution', 'All Determinants', 'All Outcomes',
       'Binge Drinking', 'Binge Drinking - $25-$49,999',
       'Binge Drinking - $50-$74,999', 'Binge Drinking - $75,000 or More',
       'Binge Drinking - Ages 18-44', 'Binge Drinking - Ages 45-64',
       'Binge Drinking - Ages 65+',
       'Binge Drinking - American Indian/Alaskan Native',
       'Binge Drinking - Asian', 'Binge Drinking - Black',
       'Binge Drinking - College Grad', 'Binge Drinking - Female',
       'Binge Drinking - Hawaiian/Pacific Islander',
       'Binge Drinking - High School Grad', 'Binge Drinking - Hispanic',
       'Binge Drinking - Less Than $25,000',
       'Binge Drinking - Less Than High School', 'Binge Drinking - Male',
       'Binge Drinking - Rural', 'Binge Drinking - Some College',
       'Binge Drinking - Suburban', 'Binge Drinking - Urban',
       'Binge Drinking - White', 'Cancer Deaths',
       'Cancer Deaths - American Indian/Alaska Native',
       'Cancer Deaths - Asian/Pacific Islander',
       'Cancer Deaths - Black/African American',
       'Cancer Deaths - Crude Rate', 'Cancer Deaths - Female',
       'Cancer Deaths - Hispanic/Latino', 'Cancer Deaths - Male',
       'Cancer Deaths - Standard Age Adjustment', 'Cancer Deaths - White',
       'Cardiovascular Deaths',
       'Cardiovascular Deaths - American Indian/Alaska Native',
       'Cardiovascular Deaths - Asian/Pacific Islander',
       'Cardiovascular Deaths - Black/African American',
       'Cardiovascular Deaths - Crude Rate',
       'Cardiovascular Deaths - Female',
       'Cardiovascular Deaths - Hispanic/Latino',
       'Cardiovascular Deaths - Male',
       'Cardiovascular Deaths - Standard Age Adjustment',
       'Cardiovascular Deaths - White', 'Children in Poverty',
       'Chlamydia', 'Chlamydia - American Indian/Alaska Native',
       'Chlamydia - Asian', 'Chlamydia - Black/African American',
       'Chlamydia - Female', 'Chlamydia - Hispanic/Latino',
       'Chlamydia - Male', 'Chlamydia - White', 'Cholesterol Check',
       'Cholesterol Check - $25-$49,999',
       'Cholesterol Check - $50-$74,999',
       'Cholesterol Check - $75,000 or More',
       'Cholesterol Check - Ages 18-44', 'Cholesterol Check - Ages 45-64',
       'Cholesterol Check - Ages 65+',
       'Cholesterol Check - American Indian/Alaskan Native',
       'Cholesterol Check - Asian', 'Cholesterol Check - Black',
       'Cholesterol Check - College Grad', 'Cholesterol Check - Female',
       'Cholesterol Check - Hawaiian/Pacific Islander',
       'Cholesterol Check - High School Grad',
       'Cholesterol Check - Hispanic',
       'Cholesterol Check - Less Than $25,000',
       'Cholesterol Check - Less Than High School',
       'Cholesterol Check - Male', 'Cholesterol Check - Rural',
       'Cholesterol Check - Some College', 'Cholesterol Check - Suburban',
       'Cholesterol Check - Urban', 'Cholesterol Check - White',
       'Colorectal Cancer Screening',
       'Colorectal Cancer Screening - $25-$49,999',
       'Colorectal Cancer Screening - $50-$74,999',
       'Colorectal Cancer Screening - $75,000 or More',
       'Colorectal Cancer Screening - American Indian/Alaskan Native',
       'Colorectal Cancer Screening - Asian',
       'Colorectal Cancer Screening - Black',
       'Colorectal Cancer Screening - College Grad',
       'Colorectal Cancer Screening - Female',
       'Colorectal Cancer Screening - Hawaiian/Pacific Islander',
       'Colorectal Cancer Screening - High School Grad',
       'Colorectal Cancer Screening - Hispanic',
       'Colorectal Cancer Screening - Less Than $25,000',
       'Colorectal Cancer Screening - Less Than High School',
       'Colorectal Cancer Screening - Male',
       'Colorectal Cancer Screening - Rural',
       'Colorectal Cancer Screening - Some College',
       'Colorectal Cancer Screening - Suburban',
       'Colorectal Cancer Screening - Urban',
       'Colorectal Cancer Screening - White',
       'Dedicated HC Provider - $25-$49,999',
       'Dedicated HC Provider - $50-$74,999',
       'Dedicated HC Provider - $75,000 or More',
       'Dedicated HC Provider - 18-44', 'Dedicated HC Provider - 45-64',
       'Dedicated HC Provider - 65+',
       'Dedicated HC Provider - American Indian/Alaskan Native',
       'Dedicated HC Provider - Asian', 'Dedicated HC Provider - Black',
       'Dedicated HC Provider - College Grad',
       'Dedicated HC Provider - Female',
       'Dedicated HC Provider - Hawaiian/Pacific Islander',
       'Dedicated HC Provider - High School Grad',
       'Dedicated HC Provider - Hispanic',
       'Dedicated HC Provider - Less Than $25,000',
       'Dedicated HC Provider - Less Than High School',
       'Dedicated HC Provider - Male', 'Dedicated HC Provider - Rural',
       'Dedicated HC Provider - Some College',
       'Dedicated HC Provider - Suburban',
       'Dedicated HC Provider - Urban', 'Dedicated HC Provider - White',
       'Dedicated Health Care Provider', 'Dental Visit - $25-$49,999',
       'Dental Visit - $50-$74,999', 'Dental Visit - $75,000 or More',
       'Dental Visit - Ages 18-44', 'Dental Visit - Ages 45-64',
       'Dental Visit - Ages 65+',
       'Dental Visit - American Indian/Alaskan Native',
       'Dental Visit - Asian', 'Dental Visit - Black',
       'Dental Visit - College Grad', 'Dental Visit - Female',
       'Dental Visit - Hawaiian/Pacific Islander',
       'Dental Visit - High School Grad', 'Dental Visit - Hispanic',
       'Dental Visit - Less Than $25,000',
       'Dental Visit - Less Than High School', 'Dental Visit - Male',
       'Dental Visit - Rural', 'Dental Visit - Some College',
       'Dental Visit - Suburban', 'Dental Visit - Urban',
       'Dental Visit - White', 'Dental Visit, Annual', 'Dentists',
       'Diabetes', 'Diabetes - $25-$49,999', 'Diabetes - $50-$74,999',
       'Diabetes - $75,000 or More', 'Diabetes - Ages 18-44',
       'Diabetes - Ages 45-64', 'Diabetes - Ages 65+',
       'Diabetes - American Indian/Alaskan Native', 'Diabetes - Asian',
       'Diabetes - Black', 'Diabetes - College Grad', 'Diabetes - Female',
       'Diabetes - Hawaiian/Pacific Islander',
       'Diabetes - High School Grad', 'Diabetes - Hispanic',
       'Diabetes - Less Than $25,000', 'Diabetes - Less Than High School',
       'Diabetes - Male', 'Diabetes - Rural', 'Diabetes - Some College',
       'Diabetes - Suburban', 'Diabetes - Urban', 'Diabetes - White',
       'Disparity in Health Status', 'Drug Deaths',
       'Drug Deaths - American Indian/Alaska Native',
       'Drug Deaths - Asian/Pacific Islander',
       'Drug Deaths - Black/African American', 'Drug Deaths - Female',
       'Drug Deaths - Hispanic/Latino', 'Drug Deaths - Male',
       'Drug Deaths - White', 'Excessive Drinking',
       'Excessive Drinking - $25-$49,999',
       'Excessive Drinking - $50-$74,999',
       'Excessive Drinking - $75,000 or More',
       'Excessive Drinking - Ages 18-44',
       'Excessive Drinking - Ages 45-64', 'Excessive Drinking - Ages 65+',
       'Excessive Drinking - American Indian/Alaskan Native',
       'Excessive Drinking - Asian', 'Excessive Drinking - Black',
       'Excessive Drinking - College Grad', 'Excessive Drinking - Female',
       'Excessive Drinking - Hawaiian/Pacific Islander',
       'Excessive Drinking - High School Grad',
       'Excessive Drinking - Hispanic',
       'Excessive Drinking - Less Than $25,000',
       'Excessive Drinking - Less Than High School',
       'Excessive Drinking - Male', 'Excessive Drinking - Rural',
       'Excessive Drinking - Some College',
       'Excessive Drinking - Suburban', 'Excessive Drinking - Urban',
       'Excessive Drinking - White', 'Flu Vaccine',
       'Flu Vaccine - $25-$49,999', 'Flu Vaccine - $50-$74,999',
       'Flu Vaccine - $75,000 or More', 'Flu Vaccine - 18-44',
       'Flu Vaccine - 45-64', 'Flu Vaccine - 65+',
       'Flu Vaccine - American Indian', 'Flu Vaccine - Asian',
       'Flu Vaccine - Black', 'Flu Vaccine - College Grad',
       'Flu Vaccine - Female', 'Flu Vaccine - Hawaiian PI',
       'Flu Vaccine - High School Grad', 'Flu Vaccine - Hispanic',
       'Flu Vaccine - Less Than $25,000', 'Flu Vaccine - Less Than HS',
       'Flu Vaccine - Male', 'Flu Vaccine - Rural',
       'Flu Vaccine - Some College', 'Flu Vaccine - Suburban',
       'Flu Vaccine - Urban', 'Flu Vaccine - White',
       'Frequent Mental Distress',
       'Frequent Mental Distress - $25-$49,999',
       'Frequent Mental Distress - $50-$74,999',
       'Frequent Mental Distress - $75,000 or More',
       'Frequent Mental Distress - Ages 18-44',
       'Frequent Mental Distress - Ages 45-64',
       'Frequent Mental Distress - Ages 65+',
       'Frequent Mental Distress - American Indian/Alaskan Native',
       'Frequent Mental Distress - Asian',
       'Frequent Mental Distress - Black',
       'Frequent Mental Distress - College Grad',
       'Frequent Mental Distress - Female',
       'Frequent Mental Distress - Hawaiian/Pacific Islander',
       'Frequent Mental Distress - High School Grad',
       'Frequent Mental Distress - Hispanic',
       'Frequent Mental Distress - Less Than $25,000',
       'Frequent Mental Distress - Less Than High School',
       'Frequent Mental Distress - Male',
       'Frequent Mental Distress - Rural',
       'Frequent Mental Distress - Some College',
       'Frequent Mental Distress - Suburban',
       'Frequent Mental Distress - Urban',
       'Frequent Mental Distress - White', 'Frequent Physical Distress',
       'Frequent Physical Distress - $25-$49,999',
       'Frequent Physical Distress - $50-$74,999',
       'Frequent Physical Distress - $75,000 or More',
       'Frequent Physical Distress - Ages 18-44',
       'Frequent Physical Distress - Ages 45-64',
       'Frequent Physical Distress - Ages 65+',
       'Frequent Physical Distress - American Indian/Alaskan Native',
       'Frequent Physical Distress - Asian',
       'Frequent Physical Distress - Black',
       'Frequent Physical Distress - College Grad',
       'Frequent Physical Distress - Female',
       'Frequent Physical Distress - Hawaiian/Pacific Islander',
       'Frequent Physical Distress - High School Grad',
       'Frequent Physical Distress - Hispanic',
       'Frequent Physical Distress - Less Than $25,000',
       'Frequent Physical Distress - Less Than High School',
       'Frequent Physical Distress - Male',
       'Frequent Physical Distress - Rural',
       'Frequent Physical Distress - Some College',
       'Frequent Physical Distress - Suburban',
       'Frequent Physical Distress - Urban',
       'Frequent Physical Distress - White', 'Fruits',
       'HC Coverage - $25-$49,999', 'HC Coverage - $50-$74,999',
       'HC Coverage - $75,000 or More', 'HC Coverage - 18-44',
       'HC Coverage - 45-64', 'HC Coverage - 65+',
       'HC Coverage - American Indian', 'HC Coverage - Asian',
       'HC Coverage - Black', 'HC Coverage - College Grad',
       'HC Coverage - Female', 'HC Coverage - Hawaiian PI',
       'HC Coverage - High School Grad', 'HC Coverage - Hispanic',
       'HC Coverage - Less Than $25,000', 'HC Coverage - Less Than HS',
       'HC Coverage - Male', 'HC Coverage - Rural',
       'HC Coverage - Some College', 'HC Coverage - Suburban',
       'HC Coverage - Urban', 'HC Coverage - White',
       'Health Care Coverage', 'Heart Attack', 'Heart Disease',
       'High Blood Pressure', 'High Blood Pressure - $25-$49,999',
       'High Blood Pressure - $50-$74,999',
       'High Blood Pressure - $75,000 or More',
       'High Blood Pressure - Ages 18-44',
       'High Blood Pressure - Ages 45-64',
       'High Blood Pressure - Ages 65+',
       'High Blood Pressure - American Indian/Alaskan Native',
       'High Blood Pressure - Asian', 'High Blood Pressure - Black',
       'High Blood Pressure - College Grad',
       'High Blood Pressure - Female',
       'High Blood Pressure - Hawaiian/Pacific Islander',
       'High Blood Pressure - High School Grad',
       'High Blood Pressure - Hispanic',
       'High Blood Pressure - Less Than $25,000',
       'High Blood Pressure - Less Than High School',
       'High Blood Pressure - Male', 'High Blood Pressure - Rural',
       'High Blood Pressure - Some College',
       'High Blood Pressure - Suburban', 'High Blood Pressure - Urban',
       'High Blood Pressure - White', 'High Cholesterol',
       'High Health Status', 'High Health Status - $25-$49,999',
       'High Health Status - $50-$74,999',
       'High Health Status - $75,000 or More',
       'High Health Status - Ages 18-44',
       'High Health Status - Ages 45-64', 'High Health Status - Ages 65+',
       'High Health Status - American Indian/Alaskan Native',
       'High Health Status - Asian', 'High Health Status - Black',
       'High Health Status - College Grad', 'High Health Status - Female',
       'High Health Status - Hawaiian/Pacific Islander',
       'High Health Status - High School Grad',
       'High Health Status - Hispanic',
       'High Health Status - Less Than $25,000',
       'High Health Status - Less Than High School',
       'High Health Status - Male', 'High Health Status - Rural',
       'High Health Status - Some College',
       'High Health Status - Suburban', 'High Health Status - Urban',
       'High Health Status - White', 'High School Graduation',
       'High School Graduation - AIAN Race',
       'High School Graduation - American Indian/Alaska Native',
       'High School Graduation - API Race', nan,
       'High School Graduation - Asian/Pacific Islander',
       'High School Graduation - Black',
       'High School Graduation - Black Race',
       'High School Graduation - Females',
       'High School Graduation - Hispanic',
       'High School Graduation - Males', 'High School Graduation - White',
       'High School Graduation - White Race', 'Immunization HPV Females',
       'Immunizations - Adolescents', 'Immunizations - Children',
       'Income Disparity Ratio', 'Income Inequality - Gini Index',
       'Infant Mortality',
       'Infant Mortality - American Indian/Alaskan Native',
       'Infant Mortality - Asian', 'Infant Mortality - Black',
       'Infant Mortality - Hispanic',
       'Infant Mortality - Mother Ages 15-19',
       'Infant Mortality - Mother Ages 20-24',
       'Infant Mortality - Mother Ages 25-29',
       'Infant Mortality - Mother Ages 30-34',
       'Infant Mortality - Mother Ages 35-39',
       'Infant Mortality - Mother Ages 40-44', 'Infant Mortality - White',
       'Infectious Disease', 'Insufficient Sleep', 'Low Birthweight',
       'Low Birthweight - Black/African American',
       'Low Birthweight - College Graduate',
       'Low Birthweight - High School Graduate',
       'Low Birthweight - Hispanic',
       'Low Birthweight - Less Than High School',
       'Low Birthweight - Mother Ages 15-19',
       'Low Birthweight - Mother Ages 20-24',
       'Low Birthweight - Mother Ages 25-29',
       'Low Birthweight - Mother Ages 30-34',
       'Low Birthweight - Mother Ages 35-39',
       'Low Birthweight - Mother Ages 40-44',
       'Low Birthweight - Some College', 'Low Birthweight - White',
       'Median Household Income', 'Meningococcal Immunizations',
       'Obesity', 'Obesity - $25-$49,999', 'Obesity - $50-$74,999',
       'Obesity - $75,000 or More', 'Obesity - Ages 18-44',
       'Obesity - Ages 45-64', 'Obesity - Ages 65+',
       'Obesity - American Indian/Alaskan Native', 'Obesity - Asian',
       'Obesity - Black', 'Obesity - College Grad', 'Obesity - Female',
       'Obesity - Hawaiian/Pacific Islander',
       'Obesity - High School Grad', 'Obesity - Hispanic',
       'Obesity - Less Than $25,000', 'Obesity - Less Than High School',
       'Obesity - Male', 'Obesity - Rural', 'Obesity - Some College',
       'Obesity - Suburban', 'Obesity - Urban', 'Obesity - White',
       'Obesity - Youth', 'Occupational Fatalities', 'Overall',
       'Personal Income, Per Capita ', 'Pertussis', 'Physical Activity',
       'Physical Inactivity', 'Physical Inactivity - $25-$49,999',
       'Physical Inactivity - $50-$74,999',
       'Physical Inactivity - $75,000 or More',
       'Physical Inactivity - Ages 18-44',
       'Physical Inactivity - Ages 45-64',
       'Physical Inactivity - Ages 65+',
       'Physical Inactivity - American Indian/Alaskan Native',
       'Physical Inactivity - Asian', 'Physical Inactivity - Black',
       'Physical Inactivity - College Grad',
       'Physical Inactivity - Female',
       'Physical Inactivity - Hawaiian/Pacific Islander',
       'Physical Inactivity - High School Grad',
       'Physical Inactivity - Hispanic',
       'Physical Inactivity - Less Than $25,000',
       'Physical Inactivity - Less Than High School',
       'Physical Inactivity - Male', 'Physical Inactivity - Rural',
       'Physical Inactivity - Some College',
       'Physical Inactivity - Suburban', 'Physical Inactivity - Urban',
       'Physical Inactivity - White', 'Poor Mental Health Days',
       'Poor Mental Health Days - $25-$49,999',
       'Poor Mental Health Days - $50-$74,999',
       'Poor Mental Health Days - $75,000 or More',
       'Poor Mental Health Days - Ages 18-44',
       'Poor Mental Health Days - Ages 45-64',
       'Poor Mental Health Days - Ages 65+',
       'Poor Mental Health Days - American Indian/Alaskan Native',
       'Poor Mental Health Days - Asian',
       'Poor Mental Health Days - Black',
       'Poor Mental Health Days - College Grad',
       'Poor Mental Health Days - Female',
       'Poor Mental Health Days - Hawaiian/Pacific Islander',
       'Poor Mental Health Days - High School Grad',
       'Poor Mental Health Days - Hispanic',
       'Poor Mental Health Days - Less Than $25,000',
       'Poor Mental Health Days - Less Than High School',
       'Poor Mental Health Days - Male',
       'Poor Mental Health Days - Rural',
       'Poor Mental Health Days - Some College',
       'Poor Mental Health Days - Suburban',
       'Poor Mental Health Days - Urban',
       'Poor Mental Health Days - White', 'Poor Physical Health Days',
       'Poor Physical Health Days - $25-$49,999',
       'Poor Physical Health Days - $50-$74,999',
       'Poor Physical Health Days - $75,000 or More',
       'Poor Physical Health Days - Ages 18-44',
       'Poor Physical Health Days - Ages 45-64',
       'Poor Physical Health Days - Ages 65+',
       'Poor Physical Health Days - American Indian/Alaskan Native',
       'Poor Physical Health Days - Asian',
       'Poor Physical Health Days - Black',
       'Poor Physical Health Days - College Grad',
       'Poor Physical Health Days - Female',
       'Poor Physical Health Days - Hawaiian/Pacific Islander',
       'Poor Physical Health Days - High School Grad',
       'Poor Physical Health Days - Hispanic',
       'Poor Physical Health Days - Less Than $25,000',
       'Poor Physical Health Days - Less Than High School',
       'Poor Physical Health Days - Male',
       'Poor Physical Health Days - Rural',
       'Poor Physical Health Days - Some College',
       'Poor Physical Health Days - Suburban',
       'Poor Physical Health Days - Urban',
       'Poor Physical Health Days - White', 'Premature Death',
       'Preterm Birth', 'Preventable Hospitalizations',
       'Primary Care Physicians', 'Public Health Funding', 'Salmonella',
       'Smoking', 'Smoking - $25-$49,999', 'Smoking - $50-$74,999',
       'Smoking - $75,000 or More', 'Smoking - Ages 18-44',
       'Smoking - Ages 45-64', 'Smoking - Ages 65+',
       'Smoking - American Indian/Alaskan Native', 'Smoking - Asian',
       'Smoking - Black', 'Smoking - College Grad', 'Smoking - Female',
       'Smoking - Hawaiian/Pacific Islander',
       'Smoking - High School Grad', 'Smoking - Hispanic',
       'Smoking - Less Than $25,000', 'Smoking - Less Than High School',
       'Smoking - Male', 'Smoking - Rural', 'Smoking - Some College',
       'Smoking - Suburban', 'Smoking - Urban', 'Smoking - White',

In [6]:
#'Below poverty threshold','Cancer Deaths','Cardiovascular Deaths','Cholesterol Check','Diabetes','Drug Deaths',

In [7]:
Underemployment_Rate=df2014[df2014['Measure Name']=='Underemployment Rate']

In [8]:
Underemployment_Rate.head()

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
27570,2014,2014 Annual,Underemployment Rate,Alabama,20,12.2,-0.625,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27571,2014,2014 Annual,Underemployment Rate,Alaska,18,12.1,-0.664,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27572,2014,2014 Annual,Underemployment Rate,Arizona,48,16.0,0.859,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27573,2014,2014 Annual,Underemployment Rate,Arkansas,30,13.7,-0.039,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27574,2014,2014 Annual,Underemployment Rate,California,51,17.3,1.367,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013

In [9]:
Underemployment_Rate.isnull().any()

Edition         False
Report Type     False
Measure Name    False
State Name      False
Rank             True
Value           False
Score            True
Lower CI         True
Upper CI         True
Source          False
Source Year     False
dtype: bool

In [10]:
Underemployment_Rate.loc[Underemployment_Rate.isnull().any(axis=1)]

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
27570,2014,2014 Annual,Underemployment Rate,Alabama,20,12.2,-0.625,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27571,2014,2014 Annual,Underemployment Rate,Alaska,18,12.1,-0.664,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27572,2014,2014 Annual,Underemployment Rate,Arizona,48,16.0,0.859,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27573,2014,2014 Annual,Underemployment Rate,Arkansas,30,13.7,-0.039,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27574,2014,2014 Annual,Underemployment Rate,California,51,17.3,1.367,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27575,2014,2014 Annual,Underemployment Rate,Colorado,21,12.5,-0.508,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27576,2014,2014 Annual,Underemployment Rate,Connecticut,35,13.9,0.039,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27577,2014,2014 Annual,Underemployment Rate,Delaware,28,13.5,-0.117,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27578,2014,2014 Annual,Underemployment Rate,Florida,39,14.3,0.195,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27579,2014,2014 Annual,Underemployment Rate,Georgia,44,14.8,0.391,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27580,2014,2014 Annual,Underemployment Rate,Hawaii,13,11.5,-0.898,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27581,2014,2014 Annual,Underemployment Rate,Idaho,23,12.7,-0.430,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27582,2014,2014 Annual,Underemployment Rate,Illinois,48,16.0,0.859,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27583,2014,2014 Annual,Underemployment Rate,Indiana,25,13.2,-0.234,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27584,2014,2014 Annual,Underemployment Rate,Iowa,5,9.2,-1.797,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27585,2014,2014 Annual,Underemployment Rate,Kansas,11,11.0,-1.094,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27586,2014,2014 Annual,Underemployment Rate,Kentucky,45,15.0,0.469,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27587,2014,2014 Annual,Underemployment Rate,Louisiana,23,12.7,-0.430,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27588,2014,2014 Annual,Underemployment Rate,Maine,30,13.7,-0.039,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27589,2014,2014 Annual,Underemployment Rate,Maryland,21,12.5,-0.508,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27590,2014,2014 Annual,Underemployment Rate,Massachusetts,25,13.2,-0.234,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27591,2014,2014 Annual,Underemployment Rate,Michigan,46,15.3,0.586,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27592,2014,2014 Annual,Underemployment Rate,Minnesota,9,10.6,-1.250,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27593,2014,2014 Annual,Underemployment Rate,Mississippi,40,14.6,0.313,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27594,2014,2014 Annual,Underemployment Rate,Missouri,15,11.6,-0.859,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27595,2014,2014 Annual,Underemployment Rate,Montana,15,11.6,-0.859,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27596,2014,2014 Annual,Underemployment Rate,Nebraska,3,8.0,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27597,2014,2014 Annual,Underemployment Rate,Nevada,52,18.1,1.680,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27598,2014,2014 Annual,Underemployment Rate,New Hampshire,10,10.9,-1.133,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27599,2014,2014 Annual,Underemployment Rate,New Jersey,41,14.7,0.352,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27600,2014,2014 Annual,Underemployment Rate,New Mexico,30,13.7,-0.039,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27601,2014,2014 Annual,Underemployment Rate,New York,33,13.8,0.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27602,2014,2014 Annual,Underemployment Rate,North Carolina,41,14.7,0.352,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27603,2014,2014 Annual,Underemployment Rate,North Dakota,1,5.6,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27604,2014,2014 Annual,Underemployment Rate,Ohio,29,13.6,-0.078,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27605,2014,2014 Annual,Underemployment Rate,Oklahoma,8,10.2,-1.406,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27606,2014,2014 Annual,Underemployment Rate,Oregon,50,16.5,1.055,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27607,2014,2014 Annual,Underemployment Rate,Pennsylvania,27,13.4,-0.156,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27608,2014,2014 Annual,Underemployment Rate,Rhode Island,47,15.5,0.664,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27609,2014,2014 Annual,Underemployment Rate,South Carolina,36,14.0,0.078,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27610,2014,2014 Annual,Underemployment Rate,South Dakota,2,7.1,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27611,2014,2014 Annual,Underemployment Rate,Tennessee,41,14.7,0.352,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27612,2014,2014 Annual,Underemployment Rate,Texas,12,11.3,-0.977,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27613,2014,2014 Annual,Underemployment Rate,Utah,7,9.7,-1.602,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27614,2014,2014 Annual,Underemployment Rate,Vermont,6,9.3,-1.758,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27615,2014,2014 Annual,Underemployment Rate,Virginia,13,11.5,-0.898,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27616,2014,2014 Annual,Underemployment Rate,Washington,36,14.0,0.078,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27617,2014,2014 Annual,Underemployment Rate,West Virginia,17,12.0,-0.703,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27618,2014,2014 Annual,Underemployment Rate,Wisconsin,18,12.1,-0.664,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27619,2014,2014 Annual,Underemployment Rate,Wyoming,4,8.4,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27620,2014,2014 Annual,Underemployment Rate,United States,NaN,13.8,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27621,2014,2014 Annual,Underemployment Rate,District of Columbia,NaN,14.1,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2013

In [11]:
Underemployment_Rate = Underemployment_Rate.fillna(value=0)
Underemployment_Rate

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
27570,2014,2014 Annual,Underemployment Rate,Alabama,20,12.2,-0.625,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27571,2014,2014 Annual,Underemployment Rate,Alaska,18,12.1,-0.664,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27572,2014,2014 Annual,Underemployment Rate,Arizona,48,16.0,0.859,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27573,2014,2014 Annual,Underemployment Rate,Arkansas,30,13.7,-0.039,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27574,2014,2014 Annual,Underemployment Rate,California,51,17.3,1.367,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27575,2014,2014 Annual,Underemployment Rate,Colorado,21,12.5,-0.508,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27576,2014,2014 Annual,Underemployment Rate,Connecticut,35,13.9,0.039,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27577,2014,2014 Annual,Underemployment Rate,Delaware,28,13.5,-0.117,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27578,2014,2014 Annual,Underemployment Rate,Florida,39,14.3,0.195,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27579,2014,2014 Annual,Underemployment Rate,Georgia,44,14.8,0.391,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27580,2014,2014 Annual,Underemployment Rate,Hawaii,13,11.5,-0.898,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27581,2014,2014 Annual,Underemployment Rate,Idaho,23,12.7,-0.430,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27582,2014,2014 Annual,Underemployment Rate,Illinois,48,16.0,0.859,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27583,2014,2014 Annual,Underemployment Rate,Indiana,25,13.2,-0.234,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27584,2014,2014 Annual,Underemployment Rate,Iowa,5,9.2,-1.797,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27585,2014,2014 Annual,Underemployment Rate,Kansas,11,11.0,-1.094,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27586,2014,2014 Annual,Underemployment Rate,Kentucky,45,15.0,0.469,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27587,2014,2014 Annual,Underemployment Rate,Louisiana,23,12.7,-0.430,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27588,2014,2014 Annual,Underemployment Rate,Maine,30,13.7,-0.039,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27589,2014,2014 Annual,Underemployment Rate,Maryland,21,12.5,-0.508,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27590,2014,2014 Annual,Underemployment Rate,Massachusetts,25,13.2,-0.234,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27591,2014,2014 Annual,Underemployment Rate,Michigan,46,15.3,0.586,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27592,2014,2014 Annual,Underemployment Rate,Minnesota,9,10.6,-1.250,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27593,2014,2014 Annual,Underemployment Rate,Mississippi,40,14.6,0.313,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27594,2014,2014 Annual,Underemployment Rate,Missouri,15,11.6,-0.859,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27595,2014,2014 Annual,Underemployment Rate,Montana,15,11.6,-0.859,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27596,2014,2014 Annual,Underemployment Rate,Nebraska,3,8.0,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27597,2014,2014 Annual,Underemployment Rate,Nevada,52,18.1,1.680,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27598,2014,2014 Annual,Underemployment Rate,New Hampshire,10,10.9,-1.133,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27599,2014,2014 Annual,Underemployment Rate,New Jersey,41,14.7,0.352,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27600,2014,2014 Annual,Underemployment Rate,New Mexico,30,13.7,-0.039,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27601,2014,2014 Annual,Underemployment Rate,New York,33,13.8,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27602,2014,2014 Annual,Underemployment Rate,North Carolina,41,14.7,0.352,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27603,2014,2014 Annual,Underemployment Rate,North Dakota,1,5.6,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27604,2014,2014 Annual,Underemployment Rate,Ohio,29,13.6,-0.078,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27605,2014,2014 Annual,Underemployment Rate,Oklahoma,8,10.2,-1.406,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27606,2014,2014 Annual,Underemployment Rate,Oregon,50,16.5,1.055,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27607,2014,2014 Annual,Underemployment Rate,Pennsylvania,27,13.4,-0.156,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27608,2014,2014 Annual,Underemployment Rate,Rhode Island,47,15.5,0.664,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27609,2014,2014 Annual,Underemployment Rate,South Carolina,36,14.0,0.078,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27610,2014,2014 Annual,Underemployment Rate,South Dakota,2,7.1,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27611,2014,2014 Annual,Underemployment Rate,Tennessee,41,14.7,0.352,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27612,2014,2014 Annual,Underemployment Rate,Texas,12,11.3,-0.977,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27613,2014,2014 Annual,Underemployment Rate,Utah,7,9.7,-1.602,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27614,2014,2014 Annual,Underemployment Rate,Vermont,6,9.3,-1.758,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27615,2014,2014 Annual,Underemployment Rate,Virginia,13,11.5,-0.898,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27616,2014,2014 Annual,Underemployment Rate,Washington,36,14.0,0.078,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27617,2014,2014 Annual,Underemployment Rate,West Virginia,17,12.0,-0.703,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27618,2014,2014 Annual,Underemployment Rate,Wisconsin,18,12.1,-0.664,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27619,2014,2014 Annual,Underemployment Rate,Wyoming,4,8.4,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27620,2014,2014 Annual,Underemployment Rate,United States,0,13.8,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013
27621,2014,2014 Annual,Underemployment Rate,District of Columbia,0,14.1,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2013

In [12]:
Underemployment_Rate.count()

Edition         52
Report Type     52
Measure Name    52
State Name      52
Rank            52
Value           52
Score           52
Lower CI        52
Upper CI        52
Source          52
Source Year     52
dtype: int64

In [13]:
list(Underemployment_Rate.columns.values)

['Edition',
 'Report Type',
 'Measure Name',
 'State Name',
 'Rank',
 'Value',
 'Score',
 'Lower CI',
 'Upper CI',
 'Source',
 'Source Year']

In [14]:
Underemployment_Rate= Underemployment_Rate[["State Name",
                                "Edition", 
                              "Measure Name",
                              "Rank",
                              "Value"]]

In [15]:
Underemployment_Rate.head()

       State Name  Edition          Measure Name Rank  Value
27570     Alabama     2014  Underemployment Rate   20   12.2
27571      Alaska     2014  Underemployment Rate   18   12.1
27572     Arizona     2014  Underemployment Rate   48   16.0
27573    Arkansas     2014  Underemployment Rate   30   13.7
27574  California     2014  Underemployment Rate   51   17.3

In [16]:
Underemployment_Rate.rename(columns = {'Rank' : 'Underemployment_Rate_Rank', 
                             'Value' : 'Underemployment_Rate_Value',
                            'State Name': 'State',
                            'Edition': 'Year'}, 
                  inplace = True)

C:\Users\steph\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [17]:
Underemployment_Rate.head()

,State,Year,Measure Name,Underemployment_Rate_Rank,Underemployment_Rate_Value
27570,Alabama,2014,Underemployment Rate,20,12.2
27571,Alaska,2014,Underemployment Rate,18,12.1
27572,Arizona,2014,Underemployment Rate,48,16.0
27573,Arkansas,2014,Underemployment Rate,30,13.7
27574,California,2014,Underemployment Rate,51,17.3

In [18]:
Underemployment_Rate = Underemployment_Rate.drop('Measure Name',axis=1)

In [19]:
Underemployment_Rate.head()

            State  Year Underemployment_Rate_Rank  Underemployment_Rate_Value
27570     Alabama  2014                        20                        12.2
27571      Alaska  2014                        18                        12.1
27572     Arizona  2014                        48                        16.0
27573    Arkansas  2014                        30                        13.7
27574  California  2014                        51                        17.3

In [20]:
Underemployment_Rate.to_csv(os.path.join("..","..","Data","Raw","America_Health_Rankings","2014 MidStep","Underemployment_Rate.csv"),index = False)