In [1]:
import pandas as pd
from datetime import datetime
import os
import numpy as np

In [2]:
file = pd.read_csv(os.path.join("..","..","Data","Raw","America_Health_Rankings","2016-Annual.csv"))
print(file)

       Edition  Report Type        Measure Name      State Name  Rank  Value  \
0         2016  2016 Annual       Air Pollution          Alaska  33.0    8.8
1         2016  2016 Annual       Air Pollution         Alabama  36.0    9.1
2         2016  2016 Annual       Air Pollution        Arkansas  15.0    7.5
3         2016  2016 Annual       Air Pollution         Arizona  43.0    9.3
4         2016  2016 Annual       Air Pollution      California  50.0   11.4
5         2016  2016 Annual       Air Pollution        Colorado   8.0    6.6
6         2016  2016 Annual       Air Pollution     Connecticut  33.0    8.8
7         2016  2016 Annual       Air Pollution        Delaware  45.0    9.5
8         2016  2016 Annual       Air Pollution         Florida  10.0    6.8
9         2016  2016 Annual       Air Pollution         Georgia  36.0    9.1
10        2016  2016 Annual       Air Pollution          Hawaii  12.0    7.0
11        2016  2016 Annual       Air Pollution            Iowa  29.0    8.6
12        2016  2016 Annual       Air Pollution           Idaho  28.0    8.5
13        2016  2016 Annual       Air Pollution        Illinois  48.0   10.8
14        2016  2016 Annual       Air Pollution         Indiana  47.0   10.5
15        2016  2016 Annual       Air Pollution          Kansas  22.0    8.0
16        2016  2016 Annual       Air Pollution        Kentucky  36.0    9.1
17        2016  2016 Annual       Air Pollution       Louisiana  25.0    8.1
18        2016  2016 Annual       Air Pollution   Massachusetts   7.0    6.4
19        2016  2016 Annual       Air Pollution        Maryland  36.0    9.1
20        2016  2016 Annual       Air Pollution           Maine  10.0    6.8
21        2016  2016 Annual       Air Pollution        Michigan  29.0    8.6
22        2016  2016 Annual       Air Pollution       Minnesota  22.0    8.0
23        2016  2016 Annual       Air Pollution        Missouri  36.0    9.1
24        2016  2016 Annual       Air Pollution     Mississippi  25.0    8.1
25        2016  2016 Annual       Air Pollution         Montana   5.0    6.3
26        2016  2016 Annual       Air Pollution  North Carolina  22.0    8.0
27        2016  2016 Annual       Air Pollution    North Dakota   2.0    4.9
28        2016  2016 Annual       Air Pollution        Nebraska  13.0    7.3
29        2016  2016 Annual       Air Pollution   New Hampshire   8.0    6.6
...        ...          ...                 ...             ...   ...    ...
35108     2016  2016 Annual  Water Fluoridation           Maine  21.0   79.3
35109     2016  2016 Annual  Water Fluoridation        Michigan  13.0   91.7
35110     2016  2016 Annual  Water Fluoridation       Minnesota   2.0   98.8
35111     2016  2016 Annual  Water Fluoridation        Missouri  26.0   76.8
35112     2016  2016 Annual  Water Fluoridation     Mississippi  37.0   60.0
35113     2016  2016 Annual  Water Fluoridation         Montana  46.0   33.7
35114     2016  2016 Annual  Water Fluoridation  North Carolina  18.0   87.8
35115     2016  2016 Annual  Water Fluoridation    North Dakota   4.0   96.7
35116     2016  2016 Annual  Water Fluoridation        Nebraska  29.0   71.6
35117     2016  2016 Annual  Water Fluoridation   New Hampshire  44.0   46.6
35118     2016  2016 Annual  Water Fluoridation      New Jersey  49.0   14.6
35119     2016  2016 Annual  Water Fluoridation      New Mexico  25.0   77.0
35120     2016  2016 Annual  Water Fluoridation          Nevada  28.0   73.7
35121     2016  2016 Annual  Water Fluoridation        New York  30.0   71.4
35122     2016  2016 Annual  Water Fluoridation            Ohio  11.0   92.7
35123     2016  2016 Annual  Water Fluoridation        Oklahoma  36.0   62.6
35124     2016  2016 Annual  Water Fluoridation          Oregon  48.0   22.6
35125     2016  2016 Annual  Water Fluoridation    Pennsylvania  41.0   54.6
35126     2016  2016 Annual  Water Fluoridation    Rhode Island  20.0   84.5
35127     2016  2016 Annual  Water Fluoridation  South Carolina   9.0   93.6
35128     2016  2016 Annual  Water Fluoridation    South Dakota   9.0   93.6
35129     2016  2016 Annual  Water Fluoridation       Tennessee  17.0   88.1
35130     2016  2016 Annual  Water Fluoridation           Texas  22.0   79.0
35131     2016  2016 Annual  Water Fluoridation            Utah  42.0   51.7
35132     2016  2016 Annual  Water Fluoridation        Virginia   7.0   95.9
35133     2016  2016 Annual  Water Fluoridation         Vermont  40.0   56.3
35134     2016  2016 Annual  Water Fluoridation      Washington  33.0   63.9
35135     2016  2016 Annual  Water Fluoridation       Wisconsin  16.0   88.9
35136     2016  2016 Annual  Water Fluoridation   West Virginia  14.0   90.5
35137     2016  2016 Annual  Water Fluoridation         Wyoming  39.0   57.1

       Score  Lower CI  Upper CI  \
0      -0.07       NaN       NaN
1       0.13       NaN       NaN
2      -0.94       NaN       NaN
3       0.27       NaN       NaN
4       1.69       NaN       NaN
5      -1.55       NaN       NaN
6      -0.07       NaN       NaN
7       0.40       NaN       NaN
8      -1.42       NaN       NaN
9       0.13       NaN       NaN
10     -1.28       NaN       NaN
11     -0.20       NaN       NaN
12     -0.27       NaN       NaN
13      1.28       NaN       NaN
14      1.08       NaN       NaN
15     -0.61       NaN       NaN
16      0.13       NaN       NaN
17     -0.54       NaN       NaN
18     -1.69       NaN       NaN
19      0.13       NaN       NaN
20     -1.42       NaN       NaN
21     -0.20       NaN       NaN
22     -0.61       NaN       NaN
23      0.13       NaN       NaN
24     -0.54       NaN       NaN
25     -1.75       NaN       NaN
26     -0.61       NaN       NaN
27     -2.00       NaN       NaN
28     -1.08       NaN       NaN
29     -1.55       NaN       NaN
...      ...       ...       ...
35108   0.21       NaN       NaN
35109   0.76       NaN       NaN
35110   1.07       NaN       NaN
35111   0.11       NaN       NaN
35112  -0.63       NaN       NaN
35113  -1.78       NaN       NaN
35114   0.59       NaN       NaN
35115   0.98       NaN       NaN
35116  -0.12       NaN       NaN
35117  -1.22       NaN       NaN
35118  -2.00       NaN       NaN
35119   0.11       NaN       NaN
35120  -0.03       NaN       NaN
35121  -0.13       NaN       NaN
35122   0.80       NaN       NaN
35123  -0.52       NaN       NaN
35124  -2.00       NaN       NaN
35125  -0.87       NaN       NaN
35126   0.44       NaN       NaN
35127   0.84       NaN       NaN
35128   0.84       NaN       NaN
35129   0.60       NaN       NaN
35130   0.20       NaN       NaN
35131  -0.99       NaN       NaN
35132   0.94       NaN       NaN
35133  -0.79       NaN       NaN
35134  -0.46       NaN       NaN
35135   0.64       NaN       NaN
35136   0.71       NaN       NaN
35137  -0.76       NaN       NaN

                                                  Source Source Year
0      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
1      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
2      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
3      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
4      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
5      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
6      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
7      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
8      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
9      U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
10     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
11     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
12     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
13     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
14     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
15     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
16     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
17     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
18     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
19     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
20     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
21     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
22     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
23     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
24     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
25     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
26     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
27     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
28     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
29     U.S. Environmental Protection Agency; U.S. Cen...   2013-2015
...                                                  ...         ...
35108           CDC, Water Fluoridation Reporting System        2014
35109           CDC, Water Fluoridation Reporting System        2014
35110           CDC, Water Fluoridation Reporting System        2014
35111           CDC, Water Fluoridation Reporting System        2014
35112           CDC, Water Fluoridation Reporting System        2014
35113           CDC, Water Fluoridation Reporting System        2014
35114           CDC, Water Fluoridation Reporting System        2014
35115           CDC, Water Fluoridation Reporting System        2014
35116           CDC, Water Fluoridation Reporting System        2014
35117           CDC, Water Fluoridation Reporting System        2014
35118           CDC, Water Fluoridation Reporting System        2014
35119           CDC, Water Fluoridation Reporting System        2014
35120           CDC, Water Fluoridation Reporting System        2014
35121           CDC, Water Fluoridation Reporting System        2014
35122           CDC, Water Fluoridation Reporting System        2014
35123           CDC, Water Fluoridation Reporting System        2014
35124           CDC, Water Fluoridation Reporting System        2014
35125           CDC, Water Fluoridation Reporting System        2014
35126           CDC, Water Fluoridation Reporting System        2014
35127           CDC, Water Fluoridation Reporting System        2014
35128           CDC, Water Fluoridation Reporting System        2014
35129           CDC, Water Fluoridation Reporting System        2014
35130           CDC, Water Fluoridation Reporting System        2014
35131           CDC, Water Fluoridation Reporting System        2014
35132           CDC, Water Fluoridation Reporting System        2014
35133           CDC, Water Fluoridation Reporting System        2014
35134           CDC, Water Fluoridation Reporting System        2014
35135           CDC, Water Fluoridation Reporting System        2014
35136           CDC, Water Fluoridation Reporting System        2014
35137           CDC, Water Fluoridation Reporting System        2014

[35138 rows x 11 columns]

In [3]:
df2016 = pd.DataFrame(file)
df2016.head()

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
0,2016,2016 Annual,Air Pollution,Alaska,33.0,8.8,-0.07,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2013-2015
1,2016,2016 Annual,Air Pollution,Alabama,36.0,9.1,0.13,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2013-2015
2,2016,2016 Annual,Air Pollution,Arkansas,15.0,7.5,-0.94,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2013-2015
3,2016,2016 Annual,Air Pollution,Arizona,43.0,9.3,0.27,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2013-2015
4,2016,2016 Annual,Air Pollution,California,50.0,11.4,1.69,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2013-2015

In [4]:
df2016.count()

Edition         35138
Report Type     35138
Measure Name    35138
State Name      35138
Rank            23354
Value           32046
Score           23256
Lower CI        28947
Upper CI        28947
Source          35138
Source Year     34410
dtype: int64

In [5]:
df2016['Measure Name'].unique()

array(['Air Pollution', 'All Determinants', 'All Outcomes', 'Behaviors',
       'Binge Drinking', 'Binge Drinking - $25-$49,999',
       'Binge Drinking - $50-$74,999', 'Binge Drinking - $75,000 or More',
       'Binge Drinking - Ages 18-44', 'Binge Drinking - Ages 45-64',
       'Binge Drinking - Ages 65+',
       'Binge Drinking - American Indian/Alaskan Native',
       'Binge Drinking - Asian', 'Binge Drinking - Black',
       'Binge Drinking - College Grad', 'Binge Drinking - Female',
       'Binge Drinking - Hawaiian/Pacific Islander',
       'Binge Drinking - High School Grad', 'Binge Drinking - Hispanic',
       'Binge Drinking - Less Than $25,000',
       'Binge Drinking - Less Than High School', 'Binge Drinking - Male',
       'Binge Drinking - Rural', 'Binge Drinking - Some College',
       'Binge Drinking - Suburban', 'Binge Drinking - Urban',
       'Binge Drinking - White', 'Cancer Deaths',
       'Cancer Deaths - American Indian/Alaska Native',
       'Cancer Deaths - Asian/Pacific Islander',
       'Cancer Deaths - Black/African American',
       'Cancer Deaths - Crude Rate', 'Cancer Deaths - Female',
       'Cancer Deaths - Hispanic/Latino', 'Cancer Deaths - Male',
       'Cancer Deaths - Standard Age Adjustment', 'Cancer Deaths - White',
       'Cardiovascular Deaths',
       'Cardiovascular Deaths - American Indian/Alaska Native',
       'Cardiovascular Deaths - Asian/Pacific Islander',
       'Cardiovascular Deaths - Black/African American',
       'Cardiovascular Deaths - Crude Rate',
       'Cardiovascular Deaths - Female',
       'Cardiovascular Deaths - Hispanic/Latino',
       'Cardiovascular Deaths - Male',
       'Cardiovascular Deaths - Standard Age Adjustment',
       'Cardiovascular Deaths - White', 'Children in Poverty',
       'Chlamydia', 'Chlamydia - American Indian/Alaska Native',
       'Chlamydia - Asian', 'Chlamydia - Black/African American',
       'Chlamydia - Female', 'Chlamydia - Hispanic/Latino',
       'Chlamydia - Male', 'Chlamydia - White', 'Cholesterol Check',
       'Cholesterol Check - $25-$49,999',
       'Cholesterol Check - $50-$74,999',
       'Cholesterol Check - $75,000 or More',
       'Cholesterol Check - Ages 18-44', 'Cholesterol Check - Ages 45-64',
       'Cholesterol Check - Ages 65+',
       'Cholesterol Check - American Indian/Alaskan Native',
       'Cholesterol Check - Asian', 'Cholesterol Check - Black',
       'Cholesterol Check - College Grad', 'Cholesterol Check - Female',
       'Cholesterol Check - Hawaiian/Pacific Islander',
       'Cholesterol Check - High School Grad',
       'Cholesterol Check - Hispanic',
       'Cholesterol Check - Less Than $25,000',
       'Cholesterol Check - Less Than High School',
       'Cholesterol Check - Male', 'Cholesterol Check - Rural',
       'Cholesterol Check - Some College', 'Cholesterol Check - Suburban',
       'Cholesterol Check - Urban', 'Cholesterol Check - White',
       'Chronic Drinking', 'Chronic Drinking - $25-$49,999',
       'Chronic Drinking - $50-$74,999',
       'Chronic Drinking - $75,000 or More',
       'Chronic Drinking - Ages 18-44', 'Chronic Drinking - Ages 45-64',
       'Chronic Drinking - Ages 65+',
       'Chronic Drinking - American Indian/Alaskan Native',
       'Chronic Drinking - Asian', 'Chronic Drinking - Black',
       'Chronic Drinking - College Grad', 'Chronic Drinking - Female',
       'Chronic Drinking - Hawaiian/Pacific Islander',
       'Chronic Drinking - High School Grad',
       'Chronic Drinking - Hispanic',
       'Chronic Drinking - Less Than $25,000',
       'Chronic Drinking - Less Than High School',
       'Chronic Drinking - Male', 'Chronic Drinking - Rural',
       'Chronic Drinking - Some College', 'Chronic Drinking - Suburban',
       'Chronic Drinking - Urban', 'Chronic Drinking - White',
       'Clinical Care', 'Colorectal Cancer Screening',
       'Colorectal Cancer Screening - $25-$49,999',
       'Colorectal Cancer Screening - $50-$74,999',
       'Colorectal Cancer Screening - $75,000 or More',
       'Colorectal Cancer Screening - American Indian/Alaskan Native',
       'Colorectal Cancer Screening - Asian',
       'Colorectal Cancer Screening - Black',
       'Colorectal Cancer Screening - College Grad',
       'Colorectal Cancer Screening - Female',
       'Colorectal Cancer Screening - Hawaiian/Pacific Islander',
       'Colorectal Cancer Screening - High School Grad',
       'Colorectal Cancer Screening - Hispanic',
       'Colorectal Cancer Screening - Less Than $25,000',
       'Colorectal Cancer Screening - Less Than High School',
       'Colorectal Cancer Screening - Male',
       'Colorectal Cancer Screening - Rural',
       'Colorectal Cancer Screening - Some College',
       'Colorectal Cancer Screening - Suburban',
       'Colorectal Cancer Screening - Urban',
       'Colorectal Cancer Screening - White', 'Community & Environment',
       'Dedicated HC Provider - $25-$49,999',
       'Dedicated HC Provider - $50-$74,999',
       'Dedicated HC Provider - $75,000 or More',
       'Dedicated HC Provider - 18-44', 'Dedicated HC Provider - 45-64',
       'Dedicated HC Provider - 65+',
       'Dedicated HC Provider - American Indian/Alaskan Native',
       'Dedicated HC Provider - Asian', 'Dedicated HC Provider - Black',
       'Dedicated HC Provider - College Grad',
       'Dedicated HC Provider - Female',
       'Dedicated HC Provider - Hawaiian/Pacific Islander',
       'Dedicated HC Provider - High School Grad',
       'Dedicated HC Provider - Hispanic',
       'Dedicated HC Provider - Less Than $25,000',
       'Dedicated HC Provider - Less Than High School',
       'Dedicated HC Provider - Male', 'Dedicated HC Provider - Rural',
       'Dedicated HC Provider - Some College',
       'Dedicated HC Provider - Suburban',
       'Dedicated HC Provider - Urban', 'Dedicated HC Provider - White',
       'Dedicated Health Care Provider', 'Dental Visit - $25-$49,999',
       'Dental Visit - $50-$74,999', 'Dental Visit - $75,000 or More',
       'Dental Visit - Ages 18-44', 'Dental Visit - Ages 45-64',
       'Dental Visit - Ages 65+',
       'Dental Visit - American Indian/Alaskan Native',
       'Dental Visit - Asian', 'Dental Visit - Black',
       'Dental Visit - College Grad', 'Dental Visit - Female',
       'Dental Visit - Hawaiian/Pacific Islander',
       'Dental Visit - High School Grad', 'Dental Visit - Hispanic',
       'Dental Visit - Less Than $25,000',
       'Dental Visit - Less Than High School', 'Dental Visit - Male',
       'Dental Visit - Rural', 'Dental Visit - Some College',
       'Dental Visit - Suburban', 'Dental Visit - Urban',
       'Dental Visit - White', 'Dental Visit, Annual', 'Dentists',
       'Diabetes', 'Diabetes - $25-$49,999', 'Diabetes - $50-$74,999',
       'Diabetes - $75,000 or More', 'Diabetes - Ages 18-44',
       'Diabetes - Ages 45-64', 'Diabetes - Ages 65+',
       'Diabetes - American Indian/Alaskan Native', 'Diabetes - Asian',
       'Diabetes - Black', 'Diabetes - College Grad', 'Diabetes - Female',
       'Diabetes - Hawaiian/Pacific Islander',
       'Diabetes - High School Grad', 'Diabetes - Hispanic',
       'Diabetes - Less Than $25,000', 'Diabetes - Less Than High School',
       'Diabetes - Male', 'Diabetes - Rural', 'Diabetes - Some College',
       'Diabetes - Suburban', 'Diabetes - Urban', 'Diabetes - White',
       'Disparity in Health Status', 'Drug Deaths',
       'Drug Deaths - American Indian/Alaska Native',
       'Drug Deaths - Asian/Pacific Islander',
       'Drug Deaths - Black/African American', 'Drug Deaths - Female',
       'Drug Deaths - Hispanic/Latino', 'Drug Deaths - Male',
       'Drug Deaths - White', 'Excessive Drinking',
       'Excessive Drinking - $25-$49,999',
       'Excessive Drinking - $50-$74,999',
       'Excessive Drinking - $75,000 or More',
       'Excessive Drinking - Ages 18-44',
       'Excessive Drinking - Ages 45-64', 'Excessive Drinking - Ages 65+',
       'Excessive Drinking - American Indian/Alaskan Native',
       'Excessive Drinking - Asian', 'Excessive Drinking - Black',
       'Excessive Drinking - College Grad', 'Excessive Drinking - Female',
       'Excessive Drinking - Hawaiian/Pacific Islander',
       'Excessive Drinking - High School Grad',
       'Excessive Drinking - Hispanic',
       'Excessive Drinking - Less Than $25,000',
       'Excessive Drinking - Less Than High School',
       'Excessive Drinking - Male', 'Excessive Drinking - Rural',
       'Excessive Drinking - Some College',
       'Excessive Drinking - Suburban', 'Excessive Drinking - Urban',
       'Excessive Drinking - White', 'Excessive Drinking Rate of Change',
       'Excessive Drinking Rate of Change-College Graduate',
       'Excessive Drinking Rate of Change-High School Grad',
       'Excessive Drinking Rate of Change-Less Than High S',
       'Excessive Drinking Rate of Change-Some College',
       'Frequent Mental Distress',
       'Frequent Mental Distress - $25-$49,999',
       'Frequent Mental Distress - $50-$74,999',
       'Frequent Mental Distress - $75,000 or More',
       'Frequent Mental Distress - Ages 18-44',
       'Frequent Mental Distress - Ages 45-64',
       'Frequent Mental Distress - Ages 65+',
       'Frequent Mental Distress - American Indian/Alaskan Native',
       'Frequent Mental Distress - Asian',
       'Frequent Mental Distress - Black',
       'Frequent Mental Distress - College Grad',
       'Frequent Mental Distress - Female',
       'Frequent Mental Distress - Hawaiian/Pacific Islander',
       'Frequent Mental Distress - High School Grad',
       'Frequent Mental Distress - Hispanic',
       'Frequent Mental Distress - Less Than $25,000',
       'Frequent Mental Distress - Less Than High School',
       'Frequent Mental Distress - Male',
       'Frequent Mental Distress - Rural',
       'Frequent Mental Distress - Some College',
       'Frequent Mental Distress - Suburban',
       'Frequent Mental Distress - Urban',
       'Frequent Mental Distress - White', 'Frequent Physical Distress',
       'Frequent Physical Distress - $25-$49,999',
       'Frequent Physical Distress - $50-$74,999',
       'Frequent Physical Distress - $75,000 or More',
       'Frequent Physical Distress - Ages 18-44',
       'Frequent Physical Distress - Ages 45-64',
       'Frequent Physical Distress - Ages 65+',
       'Frequent Physical Distress - American Indian/Alaskan Native',
       'Frequent Physical Distress - Asian',
       'Frequent Physical Distress - Black',
       'Frequent Physical Distress - College Grad',
       'Frequent Physical Distress - Female',
       'Frequent Physical Distress - Hawaiian/Pacific Islander',
       'Frequent Physical Distress - High School Grad',
       'Frequent Physical Distress - Hispanic',
       'Frequent Physical Distress - Less Than $25,000',
       'Frequent Physical Distress - Less Than High School',
       'Frequent Physical Distress - Male',
       'Frequent Physical Distress - Rural',
       'Frequent Physical Distress - Some College',
       'Frequent Physical Distress - Suburban',
       'Frequent Physical Distress - Urban',
       'Frequent Physical Distress - White', 'Fruits', 'Heart Attack',
       'Heart Attack - $25-$49,999', 'Heart Attack - $50-$74,999',
       'Heart Attack - $75,000 or More', 'Heart Attack - Ages 18-44',
       'Heart Attack - Ages 45-64', 'Heart Attack - Ages 65+',
       'Heart Attack - American Indian/Alaskan Native',
       'Heart Attack - Asian', 'Heart Attack - Black',
       'Heart Attack - College Grad', 'Heart Attack - Female',
       'Heart Attack - Hawaiian/Pacific Islander',
       'Heart Attack - High School Grad', 'Heart Attack - Hispanic',
       'Heart Attack - Less Than $25,000',
       'Heart Attack - Less Than High School', 'Heart Attack - Male',
       'Heart Attack - Rural', 'Heart Attack - Some College',
       'Heart Attack - Suburban', 'Heart Attack - Urban',
       'Heart Attack - White', 'Heart Disease',
       'Heart Disease - $25-$49,999', 'Heart Disease - $50-$74,999',
       'Heart Disease - $75,000 or More', 'Heart Disease - Ages 18-44',
       'Heart Disease - Ages 45-64', 'Heart Disease - Ages 65+',
       'Heart Disease - American Indian/Alaskan Native',
       'Heart Disease - Asian', 'Heart Disease - Black',
       'Heart Disease - College Grad', 'Heart Disease - Female',
       'Heart Disease - Hawaiian/Pacific Islander',
       'Heart Disease - High School Grad', 'Heart Disease - Hispanic',
       'Heart Disease - Less Than $25,000',
       'Heart Disease - Less Than High School', 'Heart Disease - Male',
       'Heart Disease - Rural', 'Heart Disease - Some College',
       'Heart Disease - Suburban', 'Heart Disease - Urban',
       'Heart Disease - White', 'High Blood Pressure',
       'High Blood Pressure - $25-$49,999',
       'High Blood Pressure - $50-$74,999',
       'High Blood Pressure - $75,000 or More',
       'High Blood Pressure - Ages 18-44',
       'High Blood Pressure - Ages 45-64',
       'High Blood Pressure - Ages 65+',
       'High Blood Pressure - American Indian/Alaskan Native',
       'High Blood Pressure - Asian', 'High Blood Pressure - Black',
       'High Blood Pressure - College Grad',
       'High Blood Pressure - Female',
       'High Blood Pressure - Hawaiian/Pacific Islander',
       'High Blood Pressure - High School Grad',
       'High Blood Pressure - Hispanic',
       'High Blood Pressure - Less Than $25,000',
       'High Blood Pressure - Less Than High School',
       'High Blood Pressure - Male', 'High Blood Pressure - Rural',
       'High Blood Pressure - Some College',
       'High Blood Pressure - Suburban', 'High Blood Pressure - Urban',
       'High Blood Pressure - White', 'High Cholesterol',
       'High Health Status', 'High Health Status - $25-$49,999',
       'High Health Status - $50-$74,999',
       'High Health Status - $75,000 or More',
       'High Health Status - Ages 18-44',
       'High Health Status - Ages 45-64', 'High Health Status - Ages 65+',
       'High Health Status - American Indian/Alaskan Native',
       'High Health Status - Asian', 'High Health Status - Black',
       'High Health Status - College Grad', 'High Health Status - Female',
       'High Health Status - Hawaiian/Pacific Islander',
       'High Health Status - High School Grad',
       'High Health Status - Hispanic',
       'High Health Status - Less Than $25,000',
       'High Health Status - Less Than High School',
       'High Health Status - Male', 'High Health Status - Rural',
       'High Health Status - Some College',
       'High Health Status - Suburban', 'High Health Status - Urban',
       'High Health Status - White', 'High School Graduation',
       'High School Graduation - American Indian/Alaska Native',
       'High School Graduation - Asian/Pacific Islander',
       'High School Graduation - Black',
       'High School Graduation - Hispanic',
       'High School Graduation - White', 'Immunization HPV Females',
       'Immunization HPV Females - Above Poverty',
       'Immunization HPV Females - Below Poverty',
       'Immunization HPV Females - Black',
       'Immunization HPV Females - Hispanic',
       'Immunization HPV Females - White', 'Immunization HPV Males',
       'Immunization HPV Males - Above Poverty',
       'Immunization HPV Males - Below Poverty',
       'Immunization HPV Males - Black',
       'Immunization HPV Males - Hispanic',
       'Immunization HPV Males - White', 'Immunizations - Adolescents',
       'Immunizations - Children', 'Income Disparity Ratio',
       'Income Inequality - Gini Index', 'Infant Mortality',
       'Infant Mortality - American Indian/Alaskan Native',
       'Infant Mortality - Asian', 'Infant Mortality - Black',
       'Infant Mortality - Hispanic',
       'Infant Mortality - Mother Ages 15-19',
       'Infant Mortality - Mother Ages 20-24',
       'Infant Mortality - Mother Ages 25-29',
       'Infant Mortality - Mother Ages 30-34',
       'Infant Mortality - Mother Ages 35-39',
       'Infant Mortality - Mother Ages 40-44', 'Infant Mortality - White',
       'Infectious Disease', 'Injury Deaths',
       'Injury Deaths - Ages 15-24', 'Injury Deaths - Ages 25-34',
       'Injury Deaths - Ages 35-44', 'Injury Deaths - Ages 45-54',
       'Injury Deaths - Ages 5-14', 'Injury Deaths - Ages 55-64',
       'Injury Deaths - Ages 65-74',
       'Injury Deaths - American Indian/Alaskan Native',
       'Injury Deaths - Asian/Pacific Islander', 'Injury Deaths - Black',
       'Injury Deaths - Female', 'Injury Deaths - Hispanic',
       'Injury Deaths - Male', 'Injury Deaths - White',
       'Insufficient Sleep', 'Insufficient Sleep - $25-$49,999',
       'Insufficient Sleep - $50-$74,999',
       'Insufficient Sleep - $75,000 or More',
       'Insufficient Sleep - Ages 18-44',
       'Insufficient Sleep - Ages 45-64', 'Insufficient Sleep - Ages 65+',
       'Insufficient Sleep - American Indian/Alaskan Native',
       'Insufficient Sleep - Asian', 'Insufficient Sleep - Black',
       'Insufficient Sleep - College Grad', 'Insufficient Sleep - Female',
       'Insufficient Sleep - Hawaiian/Pacific Islander',
       'Insufficient Sleep - High School Grad',
       'Insufficient Sleep - Hispanic',
       'Insufficient Sleep - Less Than $25,000',
       'Insufficient Sleep - Less Than High School',
       'Insufficient Sleep - Male', 'Insufficient Sleep - Rural',
       'Insufficient Sleep - Some College',
       'Insufficient Sleep - Suburban', 'Insufficient Sleep - Urban',
       'Insufficient Sleep - White', 'Low Birthweight',
       'Low Birthweight - Black/African American',
       'Low Birthweight - College Graduate',
       'Low Birthweight - High School Graduate',
       'Low Birthweight - Hispanic',
       'Low Birthweight - Less Than High School',
       'Low Birthweight - Mother Ages 15-19',
       'Low Birthweight - Mother Ages 20-24',
       'Low Birthweight - Mother Ages 25-29',
       'Low Birthweight - Mother Ages 30-34',
       'Low Birthweight - Mother Ages 35-39',
       'Low Birthweight - Mother Ages 40-44',
       'Low Birthweight - Some College', 'Low Birthweight - White',
       'Median Household Income', 'Meningococcal Immunizations',
       'Obesity', 'Obesity - $25-$49,999', 'Obesity - $50-$74,999',
       'Obesity - $75,000 or More', 'Obesity - Ages 18-44',
       'Obesity - Ages 45-64', 'Obesity - Ages 65+',
       'Obesity - American Indian/Alaskan Native', 'Obesity - Asian',
       'Obesity - Black', 'Obesity - College Grad', 'Obesity - Female',
       'Obesity - Hawaiian/Pacific Islander',
       'Obesity - High School Grad', 'Obesity - Hispanic',
       'Obesity - Less Than $25,000', 'Obesity - Less Than High School',
       'Obesity - Male', 'Obesity - Rural', 'Obesity - Some College',
       'Obesity - Suburban', 'Obesity - Urban', 'Obesity - White',
       'Obesity Rate of Change',
       'Obesity Rate of Change-College Graduate',
       'Obesity Rate of Change-High School Graduate',
       'Obesity Rate of Change-Less Than High School',
       'Obesity Rate of Change-Some College', 'Occupational Fatalities',
       'Overall', 'Personal Income, Per Capita ', 'Pertussis',
       'Physical Inactivity', 'Physical Inactivity - $25-$49,999',
       'Physical Inactivity - $50-$74,999',
       'Physical Inactivity - $75,000 or More',
       'Physical Inactivity - Ages 18-44',
       'Physical Inactivity - Ages 45-64',
       'Physical Inactivity - Ages 65+',
       'Physical Inactivity - American Indian/Alaskan Native',
       'Physical Inactivity - Asian', 'Physical Inactivity - Black',
       'Physical Inactivity - College Grad',
       'Physical Inactivity - Female',
       'Physical Inactivity - Hawaiian/Pacific Islander',
       'Physical Inactivity - High School Grad',
       'Physical Inactivity - Hispanic',
       'Physical Inactivity - Less Than $25,000',
       'Physical Inactivity - Less Than High School',

In [6]:
#'Below poverty threshold','Cancer Deaths','Cardiovascular Deaths','Cholesterol Check','Diabetes','Drug Deaths',

In [7]:
Unemployment_Rate=df2016[df2016['Measure Name']=='Unemployment Rate, Annual']

In [8]:
Unemployment_Rate.head()

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
34254,2016,2016 Annual,"Unemployment Rate, Annual",Alaska,47.0,6.7,1.308,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34255,2016,2016 Annual,"Unemployment Rate, Annual",Alabama,43.0,6.1,0.747,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34256,2016,2016 Annual,"Unemployment Rate, Annual",United States,NaN,5.3,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34257,2016,2016 Annual,"Unemployment Rate, Annual",Arkansas,25.0,5.2,-0.093,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34258,2016,2016 Annual,"Unemployment Rate, Annual",Arizona,42.0,6.0,0.654,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015

In [9]:
Unemployment_Rate.isnull().any()

Edition         False
Report Type     False
Measure Name    False
State Name      False
Rank             True
Value           False
Score            True
Lower CI         True
Upper CI         True
Source          False
Source Year     False
dtype: bool

In [10]:
Unemployment_Rate.loc[Unemployment_Rate.isnull().any(axis=1)]

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
34254,2016,2016 Annual,"Unemployment Rate, Annual",Alaska,47.0,6.7,1.308,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34255,2016,2016 Annual,"Unemployment Rate, Annual",Alabama,43.0,6.1,0.747,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34256,2016,2016 Annual,"Unemployment Rate, Annual",United States,NaN,5.3,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34257,2016,2016 Annual,"Unemployment Rate, Annual",Arkansas,25.0,5.2,-0.093,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34258,2016,2016 Annual,"Unemployment Rate, Annual",Arizona,42.0,6.0,0.654,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34259,2016,2016 Annual,"Unemployment Rate, Annual",California,44.0,6.2,0.841,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34260,2016,2016 Annual,"Unemployment Rate, Annual",Colorado,10.0,3.9,-1.308,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34261,2016,2016 Annual,"Unemployment Rate, Annual",Connecticut,32.0,5.6,0.280,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34262,2016,2016 Annual,"Unemployment Rate, Annual",District of Columbia,NaN,6.9,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34263,2016,2016 Annual,"Unemployment Rate, Annual",Delaware,23.0,5.0,-0.280,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34264,2016,2016 Annual,"Unemployment Rate, Annual",Florida,29.0,5.4,0.093,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34265,2016,2016 Annual,"Unemployment Rate, Annual",Georgia,36.0,5.8,0.467,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34266,2016,2016 Annual,"Unemployment Rate, Annual",Hawaii,8.0,3.7,-1.495,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34267,2016,2016 Annual,"Unemployment Rate, Annual",Iowa,5.0,3.6,-1.588,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34268,2016,2016 Annual,"Unemployment Rate, Annual",Idaho,13.0,4.3,-0.934,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34269,2016,2016 Annual,"Unemployment Rate, Annual",Illinois,38.0,5.9,0.561,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34270,2016,2016 Annual,"Unemployment Rate, Annual",Indiana,20.0,4.8,-0.467,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34271,2016,2016 Annual,"Unemployment Rate, Annual",Kansas,13.0,4.3,-0.934,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34272,2016,2016 Annual,"Unemployment Rate, Annual",Kentucky,29.0,5.4,0.093,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34273,2016,2016 Annual,"Unemployment Rate, Annual",Louisiana,44.0,6.2,0.841,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34274,2016,2016 Annual,"Unemployment Rate, Annual",Massachusetts,21.0,4.9,-0.374,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34275,2016,2016 Annual,"Unemployment Rate, Annual",Maryland,25.0,5.2,-0.093,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34276,2016,2016 Annual,"Unemployment Rate, Annual",Maine,16.0,4.4,-0.841,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34277,2016,2016 Annual,"Unemployment Rate, Annual",Michigan,29.0,5.4,0.093,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34278,2016,2016 Annual,"Unemployment Rate, Annual",Minnesota,9.0,3.8,-1.401,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34279,2016,2016 Annual,"Unemployment Rate, Annual",Missouri,23.0,5.0,-0.280,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34280,2016,2016 Annual,"Unemployment Rate, Annual",Mississippi,46.0,6.5,1.121,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34281,2016,2016 Annual,"Unemployment Rate, Annual",Montana,11.0,4.1,-1.121,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34282,2016,2016 Annual,"Unemployment Rate, Annual",North Carolina,38.0,5.9,0.561,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34283,2016,2016 Annual,"Unemployment Rate, Annual",North Dakota,1.0,2.7,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34284,2016,2016 Annual,"Unemployment Rate, Annual",Nebraska,2.0,3.0,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34285,2016,2016 Annual,"Unemployment Rate, Annual",New Hampshire,3.0,3.4,-1.775,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34286,2016,2016 Annual,"Unemployment Rate, Annual",New Jersey,36.0,5.8,0.467,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34287,2016,2016 Annual,"Unemployment Rate, Annual",New Mexico,48.0,6.8,1.401,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34288,2016,2016 Annual,"Unemployment Rate, Annual",Nevada,49.0,6.9,1.495,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34289,2016,2016 Annual,"Unemployment Rate, Annual",New York,28.0,5.3,0.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34290,2016,2016 Annual,"Unemployment Rate, Annual",Ohio,21.0,4.9,-0.374,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34291,2016,2016 Annual,"Unemployment Rate, Annual",Oklahoma,13.0,4.3,-0.934,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34292,2016,2016 Annual,"Unemployment Rate, Annual",Oregon,34.0,5.7,0.374,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34293,2016,2016 Annual,"Unemployment Rate, Annual",Pennsylvania,25.0,5.2,-0.093,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34294,2016,2016 Annual,"Unemployment Rate, Annual",Rhode Island,38.0,5.9,0.561,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34295,2016,2016 Annual,"Unemployment Rate, Annual",South Carolina,38.0,5.9,0.561,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34296,2016,2016 Annual,"Unemployment Rate, Annual",South Dakota,4.0,3.5,-1.682,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34297,2016,2016 Annual,"Unemployment Rate, Annual",Tennessee,34.0,5.7,0.374,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34298,2016,2016 Annual,"Unemployment Rate, Annual",Texas,16.0,4.4,-0.841,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34299,2016,2016 Annual,"Unemployment Rate, Annual",Utah,5.0,3.6,-1.588,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34300,2016,2016 Annual,"Unemployment Rate, Annual",Virginia,18.0,4.5,-0.747,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34301,2016,2016 Annual,"Unemployment Rate, Annual",Vermont,5.0,3.6,-1.588,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34302,2016,2016 Annual,"Unemployment Rate, Annual",Washington,32.0,5.6,0.280,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34303,2016,2016 Annual,"Unemployment Rate, Annual",Wisconsin,19.0,4.6,-0.654,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34304,2016,2016 Annual,"Unemployment Rate, Annual",West Virginia,49.0,6.9,1.495,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34305,2016,2016 Annual,"Unemployment Rate, Annual",Wyoming,11.0,4.1,-1.121,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2015

In [11]:
Unemployment_Rate = Unemployment_Rate.fillna(value=0)
Unemployment_Rate

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
34254,2016,2016 Annual,"Unemployment Rate, Annual",Alaska,47.0,6.7,1.308,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34255,2016,2016 Annual,"Unemployment Rate, Annual",Alabama,43.0,6.1,0.747,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34256,2016,2016 Annual,"Unemployment Rate, Annual",United States,0.0,5.3,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34257,2016,2016 Annual,"Unemployment Rate, Annual",Arkansas,25.0,5.2,-0.093,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34258,2016,2016 Annual,"Unemployment Rate, Annual",Arizona,42.0,6.0,0.654,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34259,2016,2016 Annual,"Unemployment Rate, Annual",California,44.0,6.2,0.841,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34260,2016,2016 Annual,"Unemployment Rate, Annual",Colorado,10.0,3.9,-1.308,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34261,2016,2016 Annual,"Unemployment Rate, Annual",Connecticut,32.0,5.6,0.280,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34262,2016,2016 Annual,"Unemployment Rate, Annual",District of Columbia,0.0,6.9,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34263,2016,2016 Annual,"Unemployment Rate, Annual",Delaware,23.0,5.0,-0.280,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34264,2016,2016 Annual,"Unemployment Rate, Annual",Florida,29.0,5.4,0.093,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34265,2016,2016 Annual,"Unemployment Rate, Annual",Georgia,36.0,5.8,0.467,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34266,2016,2016 Annual,"Unemployment Rate, Annual",Hawaii,8.0,3.7,-1.495,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34267,2016,2016 Annual,"Unemployment Rate, Annual",Iowa,5.0,3.6,-1.588,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34268,2016,2016 Annual,"Unemployment Rate, Annual",Idaho,13.0,4.3,-0.934,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34269,2016,2016 Annual,"Unemployment Rate, Annual",Illinois,38.0,5.9,0.561,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34270,2016,2016 Annual,"Unemployment Rate, Annual",Indiana,20.0,4.8,-0.467,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34271,2016,2016 Annual,"Unemployment Rate, Annual",Kansas,13.0,4.3,-0.934,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34272,2016,2016 Annual,"Unemployment Rate, Annual",Kentucky,29.0,5.4,0.093,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34273,2016,2016 Annual,"Unemployment Rate, Annual",Louisiana,44.0,6.2,0.841,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34274,2016,2016 Annual,"Unemployment Rate, Annual",Massachusetts,21.0,4.9,-0.374,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34275,2016,2016 Annual,"Unemployment Rate, Annual",Maryland,25.0,5.2,-0.093,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34276,2016,2016 Annual,"Unemployment Rate, Annual",Maine,16.0,4.4,-0.841,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34277,2016,2016 Annual,"Unemployment Rate, Annual",Michigan,29.0,5.4,0.093,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34278,2016,2016 Annual,"Unemployment Rate, Annual",Minnesota,9.0,3.8,-1.401,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34279,2016,2016 Annual,"Unemployment Rate, Annual",Missouri,23.0,5.0,-0.280,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34280,2016,2016 Annual,"Unemployment Rate, Annual",Mississippi,46.0,6.5,1.121,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34281,2016,2016 Annual,"Unemployment Rate, Annual",Montana,11.0,4.1,-1.121,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34282,2016,2016 Annual,"Unemployment Rate, Annual",North Carolina,38.0,5.9,0.561,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34283,2016,2016 Annual,"Unemployment Rate, Annual",North Dakota,1.0,2.7,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34284,2016,2016 Annual,"Unemployment Rate, Annual",Nebraska,2.0,3.0,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34285,2016,2016 Annual,"Unemployment Rate, Annual",New Hampshire,3.0,3.4,-1.775,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34286,2016,2016 Annual,"Unemployment Rate, Annual",New Jersey,36.0,5.8,0.467,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34287,2016,2016 Annual,"Unemployment Rate, Annual",New Mexico,48.0,6.8,1.401,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34288,2016,2016 Annual,"Unemployment Rate, Annual",Nevada,49.0,6.9,1.495,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34289,2016,2016 Annual,"Unemployment Rate, Annual",New York,28.0,5.3,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34290,2016,2016 Annual,"Unemployment Rate, Annual",Ohio,21.0,4.9,-0.374,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34291,2016,2016 Annual,"Unemployment Rate, Annual",Oklahoma,13.0,4.3,-0.934,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34292,2016,2016 Annual,"Unemployment Rate, Annual",Oregon,34.0,5.7,0.374,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34293,2016,2016 Annual,"Unemployment Rate, Annual",Pennsylvania,25.0,5.2,-0.093,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34294,2016,2016 Annual,"Unemployment Rate, Annual",Rhode Island,38.0,5.9,0.561,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34295,2016,2016 Annual,"Unemployment Rate, Annual",South Carolina,38.0,5.9,0.561,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34296,2016,2016 Annual,"Unemployment Rate, Annual",South Dakota,4.0,3.5,-1.682,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34297,2016,2016 Annual,"Unemployment Rate, Annual",Tennessee,34.0,5.7,0.374,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34298,2016,2016 Annual,"Unemployment Rate, Annual",Texas,16.0,4.4,-0.841,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34299,2016,2016 Annual,"Unemployment Rate, Annual",Utah,5.0,3.6,-1.588,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34300,2016,2016 Annual,"Unemployment Rate, Annual",Virginia,18.0,4.5,-0.747,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34301,2016,2016 Annual,"Unemployment Rate, Annual",Vermont,5.0,3.6,-1.588,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34302,2016,2016 Annual,"Unemployment Rate, Annual",Washington,32.0,5.6,0.280,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34303,2016,2016 Annual,"Unemployment Rate, Annual",Wisconsin,19.0,4.6,-0.654,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34304,2016,2016 Annual,"Unemployment Rate, Annual",West Virginia,49.0,6.9,1.495,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015
34305,2016,2016 Annual,"Unemployment Rate, Annual",Wyoming,11.0,4.1,-1.121,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2015

In [12]:
Unemployment_Rate.count()

Edition         52
Report Type     52
Measure Name    52
State Name      52
Rank            52
Value           52
Score           52
Lower CI        52
Upper CI        52
Source          52
Source Year     52
dtype: int64

In [13]:
list(Unemployment_Rate.columns.values)

['Edition',
 'Report Type',
 'Measure Name',
 'State Name',
 'Rank',
 'Value',
 'Score',
 'Lower CI',
 'Upper CI',
 'Source',
 'Source Year']

In [14]:
Unemployment_Rate= Unemployment_Rate[["State Name",
                                "Edition", 
                              "Measure Name",
                              "Rank",
                              "Value"]]

In [15]:
Unemployment_Rate.head()

          State Name  Edition               Measure Name  Rank  Value
34254         Alaska     2016  Unemployment Rate, Annual  47.0    6.7
34255        Alabama     2016  Unemployment Rate, Annual  43.0    6.1
34256  United States     2016  Unemployment Rate, Annual   0.0    5.3
34257       Arkansas     2016  Unemployment Rate, Annual  25.0    5.2
34258        Arizona     2016  Unemployment Rate, Annual  42.0    6.0

In [16]:
Unemployment_Rate.rename(columns = {'Rank' : 'Unemployment_Rate_Rank', 
                             'Value' : 'Unemployment_Rate_Value',
                            'State Name': 'State',
                            'Edition': 'Year'}, 
                  inplace = True)

C:\Users\steph\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [17]:
Unemployment_Rate.head()

,State,Year,Measure Name,Unemployment_Rate_Rank,Unemployment_Rate_Value
34254,Alaska,2016,"Unemployment Rate, Annual",47.0,6.7
34255,Alabama,2016,"Unemployment Rate, Annual",43.0,6.1
34256,United States,2016,"Unemployment Rate, Annual",0.0,5.3
34257,Arkansas,2016,"Unemployment Rate, Annual",25.0,5.2
34258,Arizona,2016,"Unemployment Rate, Annual",42.0,6.0

In [18]:
Unemployment_Rate = Unemployment_Rate.drop('Measure Name',axis=1)

In [19]:
Unemployment_Rate.head()

               State  Year  Unemployment_Rate_Rank  Unemployment_Rate_Value
34254         Alaska  2016                    47.0                      6.7
34255        Alabama  2016                    43.0                      6.1
34256  United States  2016                     0.0                      5.3
34257       Arkansas  2016                    25.0                      5.2
34258        Arizona  2016                    42.0                      6.0

In [20]:
Unemployment_Rate.to_csv(os.path.join("..","..","Data","Raw","America_Health_Rankings","2016 MidStep","Unemployment_Rate.csv"),index = False)