In [1]:
import pandas as pd
from datetime import datetime
import os
import numpy as np

In [2]:
file = pd.read_csv(os.path.join("..","..","Data","Raw","America_Health_Rankings","2015-Annual.csv"))
print(file)

       Edition  Report Type   Measure Name            State Name  Rank  Value  \
0         2015  2015 Annual  Air Pollution               Alabama  34.0    9.5
1         2015  2015 Annual  Air Pollution                Alaska   4.0    6.0
2         2015  2015 Annual  Air Pollution               Arizona  37.0    9.7
3         2015  2015 Annual  Air Pollution              Arkansas  37.0    9.7
4         2015  2015 Annual  Air Pollution            California  50.0   12.5
5         2015  2015 Annual  Air Pollution              Colorado   9.0    7.0
6         2015  2015 Annual  Air Pollution           Connecticut  24.0    8.8
7         2015  2015 Annual  Air Pollution              Delaware  37.0    9.7
8         2015  2015 Annual  Air Pollution               Florida  10.0    7.2
9         2015  2015 Annual  Air Pollution               Georgia  41.0    9.8
10        2015  2015 Annual  Air Pollution                Hawaii  14.0    7.6
11        2015  2015 Annual  Air Pollution                 Idaho  49.0   11.7
12        2015  2015 Annual  Air Pollution              Illinois  46.0   11.1
13        2015  2015 Annual  Air Pollution               Indiana  47.0   11.3
14        2015  2015 Annual  Air Pollution                  Iowa  32.0    9.3
15        2015  2015 Annual  Air Pollution                Kansas  21.0    8.6
16        2015  2015 Annual  Air Pollution              Kentucky  44.0   10.1
17        2015  2015 Annual  Air Pollution             Louisiana  21.0    8.6
18        2015  2015 Annual  Air Pollution                 Maine  13.0    7.4
19        2015  2015 Annual  Air Pollution              Maryland  36.0    9.6
20        2015  2015 Annual  Air Pollution         Massachusetts  10.0    7.2
21        2015  2015 Annual  Air Pollution              Michigan  24.0    8.8
22        2015  2015 Annual  Air Pollution             Minnesota  17.0    8.0
23        2015  2015 Annual  Air Pollution           Mississippi  27.0    8.9
24        2015  2015 Annual  Air Pollution              Missouri  37.0    9.7
25        2015  2015 Annual  Air Pollution               Montana   3.0    5.7
26        2015  2015 Annual  Air Pollution              Nebraska  15.0    7.8
27        2015  2015 Annual  Air Pollution                Nevada  43.0   10.0
28        2015  2015 Annual  Air Pollution         New Hampshire  10.0    7.2
29        2015  2015 Annual  Air Pollution            New Jersey  24.0    8.8
...        ...          ...            ...                   ...   ...    ...
36056     2015  2015 Annual  Youth Smoking             Minnesota   NaN    NaN
36057     2015  2015 Annual  Youth Smoking           Mississippi   NaN   17.2
36058     2015  2015 Annual  Youth Smoking              Missouri   NaN   14.9
36059     2015  2015 Annual  Youth Smoking               Montana   NaN   15.2
36060     2015  2015 Annual  Youth Smoking              Nebraska   NaN   10.9
36061     2015  2015 Annual  Youth Smoking                Nevada   NaN   10.3
36062     2015  2015 Annual  Youth Smoking         New Hampshire   NaN   13.8
36063     2015  2015 Annual  Youth Smoking            New Jersey   NaN   12.9
36064     2015  2015 Annual  Youth Smoking            New Mexico   NaN   14.4
36065     2015  2015 Annual  Youth Smoking              New York   NaN   10.6
36066     2015  2015 Annual  Youth Smoking        North Carolina   NaN   15.0
36067     2015  2015 Annual  Youth Smoking          North Dakota   NaN   19.0
36068     2015  2015 Annual  Youth Smoking                  Ohio   NaN   15.1
36069     2015  2015 Annual  Youth Smoking              Oklahoma   NaN   18.5
36070     2015  2015 Annual  Youth Smoking                Oregon   NaN    NaN
36071     2015  2015 Annual  Youth Smoking          Pennsylvania   NaN    NaN
36072     2015  2015 Annual  Youth Smoking          Rhode Island   NaN    8.0
36073     2015  2015 Annual  Youth Smoking        South Carolina   NaN   16.0
36074     2015  2015 Annual  Youth Smoking          South Dakota   NaN   16.5
36075     2015  2015 Annual  Youth Smoking             Tennessee   NaN   15.4
36076     2015  2015 Annual  Youth Smoking                 Texas   NaN   14.1
36077     2015  2015 Annual  Youth Smoking                  Utah   NaN    4.4
36078     2015  2015 Annual  Youth Smoking               Vermont   NaN    NaN
36079     2015  2015 Annual  Youth Smoking              Virginia   NaN   11.1
36080     2015  2015 Annual  Youth Smoking            Washington   NaN    NaN
36081     2015  2015 Annual  Youth Smoking         West Virginia   NaN   19.6
36082     2015  2015 Annual  Youth Smoking             Wisconsin   NaN   11.8
36083     2015  2015 Annual  Youth Smoking               Wyoming   NaN   17.4
36084     2015  2015 Annual  Youth Smoking         United States   NaN   15.7
36085     2015  2015 Annual  Youth Smoking  District of Columbia   NaN    NaN

       Score  Lower CI  Upper CI  \
0       0.00       NaN       NaN
1      -2.00       NaN       NaN
2       0.12       NaN       NaN
3       0.12       NaN       NaN
4       1.78       NaN       NaN
5      -1.49       NaN       NaN
6      -0.42       NaN       NaN
7       0.12       NaN       NaN
8      -1.37       NaN       NaN
9       0.18       NaN       NaN
10     -1.13       NaN       NaN
11      1.31       NaN       NaN
12      0.95       NaN       NaN
13      1.07       NaN       NaN
14     -0.12       NaN       NaN
15     -0.54       NaN       NaN
16      0.36       NaN       NaN
17     -0.54       NaN       NaN
18     -1.25       NaN       NaN
19      0.06       NaN       NaN
20     -1.37       NaN       NaN
21     -0.42       NaN       NaN
22     -0.89       NaN       NaN
23     -0.36       NaN       NaN
24      0.12       NaN       NaN
25     -2.00       NaN       NaN
26     -1.01       NaN       NaN
27      0.30       NaN       NaN
28     -1.37       NaN       NaN
29     -0.42       NaN       NaN
...      ...       ...       ...
36056    NaN       NaN       NaN
36057    NaN      20.4      14.5
36058    NaN      17.2      12.9
36059    NaN      17.2      13.4
36060    NaN      12.9       9.1
36061    NaN      13.2       8.1
36062    NaN      16.4      11.6
36063    NaN      15.3      10.8
36064    NaN      17.0      12.2
36065    NaN      12.2       9.3
36066    NaN      17.3      12.8
36067    NaN      21.7      16.6
36068    NaN      19.6      11.5
36069    NaN      22.0      15.5
36070    NaN       NaN       NaN
36071    NaN       NaN       NaN
36072    NaN      11.0       5.8
36073    NaN      19.0      13.3
36074    NaN      21.4      12.5
36075    NaN      18.3      13.0
36076    NaN      16.8      11.9
36077    NaN       5.9       3.2
36078    NaN       NaN       NaN
36079    NaN      12.7       9.6
36080    NaN       NaN       NaN
36081    NaN      22.7      16.8
36082    NaN      14.1       9.9
36083    NaN      20.4      14.7
36084    NaN      18.1      13.5
36085    NaN       NaN       NaN

                                                  Source Source Year
0      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
1      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
2      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
3      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
4      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
5      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
6      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
7      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
8      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
9      U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
10     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
11     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
12     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
13     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
14     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
15     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
16     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
17     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
18     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
19     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
20     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
21     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
22     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
23     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
24     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
25     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
26     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
27     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
28     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
29     U.S. Environmental Protection Agency; U.S. Cen...   2012-2014
...                                                  ...         ...
36056     CDC, Youth Behavioral Risk Surveillance System        2013
36057     CDC, Youth Behavioral Risk Surveillance System        2013
36058     CDC, Youth Behavioral Risk Surveillance System        2013
36059     CDC, Youth Behavioral Risk Surveillance System        2013
36060     CDC, Youth Behavioral Risk Surveillance System        2013
36061     CDC, Youth Behavioral Risk Surveillance System        2013
36062     CDC, Youth Behavioral Risk Surveillance System        2013
36063     CDC, Youth Behavioral Risk Surveillance System        2013
36064     CDC, Youth Behavioral Risk Surveillance System        2013
36065     CDC, Youth Behavioral Risk Surveillance System        2013
36066     CDC, Youth Behavioral Risk Surveillance System        2013
36067     CDC, Youth Behavioral Risk Surveillance System        2013
36068     CDC, Youth Behavioral Risk Surveillance System        2013
36069     CDC, Youth Behavioral Risk Surveillance System        2013
36070     CDC, Youth Behavioral Risk Surveillance System        2013
36071     CDC, Youth Behavioral Risk Surveillance System        2013
36072     CDC, Youth Behavioral Risk Surveillance System        2013
36073     CDC, Youth Behavioral Risk Surveillance System        2013
36074     CDC, Youth Behavioral Risk Surveillance System        2013
36075     CDC, Youth Behavioral Risk Surveillance System        2013
36076     CDC, Youth Behavioral Risk Surveillance System        2013
36077     CDC, Youth Behavioral Risk Surveillance System        2013
36078     CDC, Youth Behavioral Risk Surveillance System        2013
36079     CDC, Youth Behavioral Risk Surveillance System        2013
36080     CDC, Youth Behavioral Risk Surveillance System        2013
36081     CDC, Youth Behavioral Risk Surveillance System        2013
36082     CDC, Youth Behavioral Risk Surveillance System        2013
36083     CDC, Youth Behavioral Risk Surveillance System        2013
36084     CDC, Youth Behavioral Risk Surveillance System        2013
36085     CDC, Youth Behavioral Risk Surveillance System        2013

[36086 rows x 11 columns]

In [3]:
df2015 = pd.DataFrame(file)
df2015.head()

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
0,2015,2015 Annual,Air Pollution,Alabama,34.0,9.5,0.00,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2012-2014
1,2015,2015 Annual,Air Pollution,Alaska,4.0,6.0,-2.00,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2012-2014
2,2015,2015 Annual,Air Pollution,Arizona,37.0,9.7,0.12,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2012-2014
3,2015,2015 Annual,Air Pollution,Arkansas,37.0,9.7,0.12,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2012-2014
4,2015,2015 Annual,Air Pollution,California,50.0,12.5,1.78,NaN,NaN,U.S. Environmental Protection Agency; U.S. Cen...,2012-2014

In [4]:
df2015.count()

Edition         36086
Report Type     36086
Measure Name    36086
State Name      36086
Rank            23354
Value           32726
Score           22956
Lower CI        30486
Upper CI        30486
Source          36086
Source Year     35358
dtype: int64

In [5]:
df2015['Measure Name'].unique()

array(['Air Pollution', 'All Determinants', 'All Outcomes', 'Behaviors',
       'Binge Drinking', 'Binge Drinking - $25-$49,999',
       'Binge Drinking - $50-$74,999', 'Binge Drinking - $75,000 or More',
       'Binge Drinking - Ages 18-44', 'Binge Drinking - Ages 45-64',
       'Binge Drinking - Ages 65+',
       'Binge Drinking - American Indian/Alaskan Native',
       'Binge Drinking - Asian', 'Binge Drinking - Black',
       'Binge Drinking - College Grad', 'Binge Drinking - Female',
       'Binge Drinking - Hawaiian/Pacific Islander',
       'Binge Drinking - High School Grad', 'Binge Drinking - Hispanic',
       'Binge Drinking - Less Than $25,000',
       'Binge Drinking - Less Than High School', 'Binge Drinking - Male',
       'Binge Drinking - Rural', 'Binge Drinking - Some College',
       'Binge Drinking - Suburban', 'Binge Drinking - Urban',
       'Binge Drinking - White', 'Cancer Deaths',
       'Cancer Deaths - American Indian/Alaska Native',
       'Cancer Deaths - Asian/Pacific Islander',
       'Cancer Deaths - Black/African American',
       'Cancer Deaths - Crude Rate', 'Cancer Deaths - Female',
       'Cancer Deaths - Hispanic/Latino', 'Cancer Deaths - Male',
       'Cancer Deaths - Standard Age Adjustment', 'Cancer Deaths - White',
       'Cardiovascular Deaths',
       'Cardiovascular Deaths - American Indian/Alaska Native',
       'Cardiovascular Deaths - Asian/Pacific Islander',
       'Cardiovascular Deaths - Black/African American',
       'Cardiovascular Deaths - Crude Rate',
       'Cardiovascular Deaths - Female',
       'Cardiovascular Deaths - Hispanic/Latino',
       'Cardiovascular Deaths - Male',
       'Cardiovascular Deaths - Standard Age Adjustment',
       'Cardiovascular Deaths - White', 'Children in Poverty',
       'Chlamydia', 'Chlamydia - American Indian/Alaska Native',
       'Chlamydia - Asian', 'Chlamydia - Black/African American',
       'Chlamydia - Female', 'Chlamydia - Hispanic/Latino',
       'Chlamydia - Male', 'Chlamydia - White', 'Cholesterol Check',
       'Cholesterol Check - $25-$49,999',
       'Cholesterol Check - $50-$74,999',
       'Cholesterol Check - $75,000 or More',
       'Cholesterol Check - Ages 18-44', 'Cholesterol Check - Ages 45-64',
       'Cholesterol Check - Ages 65+',
       'Cholesterol Check - American Indian/Alaskan Native',
       'Cholesterol Check - Asian', 'Cholesterol Check - Black',
       'Cholesterol Check - College Grad', 'Cholesterol Check - Female',
       'Cholesterol Check - Hawaiian/Pacific Islander',
       'Cholesterol Check - High School Grad',
       'Cholesterol Check - Hispanic',
       'Cholesterol Check - Less Than $25,000',
       'Cholesterol Check - Less Than High School',
       'Cholesterol Check - Male', 'Cholesterol Check - Rural',
       'Cholesterol Check - Some College', 'Cholesterol Check - Suburban',
       'Cholesterol Check - Urban', 'Cholesterol Check - White',
       'Chronic Drinking', 'Chronic Drinking - $25-$49,999',
       'Chronic Drinking - $50-$74,999',
       'Chronic Drinking - $75,000 or More',
       'Chronic Drinking - Ages 18-44', 'Chronic Drinking - Ages 45-64',
       'Chronic Drinking - Ages 65+',
       'Chronic Drinking - American Indian/Alaskan Native',
       'Chronic Drinking - Asian', 'Chronic Drinking - Black',
       'Chronic Drinking - College Grad', 'Chronic Drinking - Female',
       'Chronic Drinking - Hawaiian/Pacific Islander',
       'Chronic Drinking - High School Grad',
       'Chronic Drinking - Hispanic',
       'Chronic Drinking - Less Than $25,000',
       'Chronic Drinking - Less Than High School',
       'Chronic Drinking - Male', 'Chronic Drinking - Rural',
       'Chronic Drinking - Some College', 'Chronic Drinking - Suburban',
       'Chronic Drinking - Urban', 'Chronic Drinking - White',
       'Clinical Care', 'Colorectal Cancer Screening',
       'Colorectal Cancer Screening - $25-$49,999',
       'Colorectal Cancer Screening - $50-$74,999',
       'Colorectal Cancer Screening - $75,000 or More',
       'Colorectal Cancer Screening - American Indian/Alaskan Native',
       'Colorectal Cancer Screening - Asian',
       'Colorectal Cancer Screening - Black',
       'Colorectal Cancer Screening - College Grad',
       'Colorectal Cancer Screening - Female',
       'Colorectal Cancer Screening - Hawaiian/Pacific Islander',
       'Colorectal Cancer Screening - High School Grad',
       'Colorectal Cancer Screening - Hispanic',
       'Colorectal Cancer Screening - Less Than $25,000',
       'Colorectal Cancer Screening - Less Than High School',
       'Colorectal Cancer Screening - Male',
       'Colorectal Cancer Screening - Rural',
       'Colorectal Cancer Screening - Some College',
       'Colorectal Cancer Screening - Suburban',
       'Colorectal Cancer Screening - Urban',
       'Colorectal Cancer Screening - White', 'Community & Environment',
       'Dedicated HC Provider - $25-$49,999',
       'Dedicated HC Provider - $50-$74,999',
       'Dedicated HC Provider - $75,000 or More',
       'Dedicated HC Provider - 18-44', 'Dedicated HC Provider - 45-64',
       'Dedicated HC Provider - 65+',
       'Dedicated HC Provider - American Indian/Alaskan Native',
       'Dedicated HC Provider - Asian', 'Dedicated HC Provider - Black',
       'Dedicated HC Provider - College Grad',
       'Dedicated HC Provider - Female',
       'Dedicated HC Provider - Hawaiian/Pacific Islander',
       'Dedicated HC Provider - High School Grad',
       'Dedicated HC Provider - Hispanic',
       'Dedicated HC Provider - Less Than $25,000',
       'Dedicated HC Provider - Less Than High School',
       'Dedicated HC Provider - Male', 'Dedicated HC Provider - Rural',
       'Dedicated HC Provider - Some College',
       'Dedicated HC Provider - Suburban',
       'Dedicated HC Provider - Urban', 'Dedicated HC Provider - White',
       'Dedicated Health Care Provider', 'Dental Visit - $25-$49,999',
       'Dental Visit - $50-$74,999', 'Dental Visit - $75,000 or More',
       'Dental Visit - Ages 18-44', 'Dental Visit - Ages 45-64',
       'Dental Visit - Ages 65+',
       'Dental Visit - American Indian/Alaskan Native',
       'Dental Visit - Asian', 'Dental Visit - Black',
       'Dental Visit - College Grad', 'Dental Visit - Female',
       'Dental Visit - Hawaiian/Pacific Islander',
       'Dental Visit - High School Grad', 'Dental Visit - Hispanic',
       'Dental Visit - Less Than $25,000',
       'Dental Visit - Less Than High School', 'Dental Visit - Male',
       'Dental Visit - Rural', 'Dental Visit - Some College',
       'Dental Visit - Suburban', 'Dental Visit - Urban',
       'Dental Visit - White', 'Dental Visit, Annual', 'Dentists',
       'Diabetes', 'Diabetes - $25-$49,999', 'Diabetes - $50-$74,999',
       'Diabetes - $75,000 or More', 'Diabetes - Ages 18-44',
       'Diabetes - Ages 45-64', 'Diabetes - Ages 65+',
       'Diabetes - American Indian/Alaskan Native', 'Diabetes - Asian',
       'Diabetes - Black', 'Diabetes - College Grad', 'Diabetes - Female',
       'Diabetes - Hawaiian/Pacific Islander',
       'Diabetes - High School Grad', 'Diabetes - Hispanic',
       'Diabetes - Less Than $25,000', 'Diabetes - Less Than High School',
       'Diabetes - Male', 'Diabetes - Rural', 'Diabetes - Some College',
       'Diabetes - Suburban', 'Diabetes - Urban', 'Diabetes - White',
       'Disparity in Health Status', 'Drug Deaths',
       'Drug Deaths - American Indian/Alaska Native',
       'Drug Deaths - Asian/Pacific Islander',
       'Drug Deaths - Black/African American', 'Drug Deaths - Female',
       'Drug Deaths - Hispanic/Latino', 'Drug Deaths - Male',
       'Drug Deaths - White', 'Excessive Drinking',
       'Excessive Drinking - $25-$49,999',
       'Excessive Drinking - $50-$74,999',
       'Excessive Drinking - $75,000 or More',
       'Excessive Drinking - Ages 18-44',
       'Excessive Drinking - Ages 45-64', 'Excessive Drinking - Ages 65+',
       'Excessive Drinking - American Indian/Alaskan Native',
       'Excessive Drinking - Asian', 'Excessive Drinking - Black',
       'Excessive Drinking - College Grad', 'Excessive Drinking - Female',
       'Excessive Drinking - Hawaiian/Pacific Islander',
       'Excessive Drinking - High School Grad',
       'Excessive Drinking - Hispanic',
       'Excessive Drinking - Less Than $25,000',
       'Excessive Drinking - Less Than High School',
       'Excessive Drinking - Male', 'Excessive Drinking - Rural',
       'Excessive Drinking - Some College',
       'Excessive Drinking - Suburban', 'Excessive Drinking - Urban',
       'Excessive Drinking - White', 'Flu Vaccine',
       'Flu Vaccine - $25-$49,999', 'Flu Vaccine - $50-$74,999',
       'Flu Vaccine - $75,000 or More', 'Flu Vaccine - 18-44',
       'Flu Vaccine - 45-64', 'Flu Vaccine - 65+',
       'Flu Vaccine - American Indian', 'Flu Vaccine - Asian',
       'Flu Vaccine - Black', 'Flu Vaccine - College Grad',
       'Flu Vaccine - Female', 'Flu Vaccine - Hawaiian PI',
       'Flu Vaccine - High School Grad', 'Flu Vaccine - Hispanic',
       'Flu Vaccine - Less Than $25,000', 'Flu Vaccine - Less Than HS',
       'Flu Vaccine - Male', 'Flu Vaccine - Rural',
       'Flu Vaccine - Some College', 'Flu Vaccine - Suburban',
       'Flu Vaccine - Urban', 'Flu Vaccine - White',
       'Frequent Mental Distress',
       'Frequent Mental Distress - $25-$49,999',
       'Frequent Mental Distress - $50-$74,999',
       'Frequent Mental Distress - $75,000 or More',
       'Frequent Mental Distress - Ages 18-44',
       'Frequent Mental Distress - Ages 45-64',
       'Frequent Mental Distress - Ages 65+',
       'Frequent Mental Distress - American Indian/Alaskan Native',
       'Frequent Mental Distress - Asian',
       'Frequent Mental Distress - Black',
       'Frequent Mental Distress - College Grad',
       'Frequent Mental Distress - Female',
       'Frequent Mental Distress - Hawaiian/Pacific Islander',
       'Frequent Mental Distress - High School Grad',
       'Frequent Mental Distress - Hispanic',
       'Frequent Mental Distress - Less Than $25,000',
       'Frequent Mental Distress - Less Than High School',
       'Frequent Mental Distress - Male',
       'Frequent Mental Distress - Rural',
       'Frequent Mental Distress - Some College',
       'Frequent Mental Distress - Suburban',
       'Frequent Mental Distress - Urban',
       'Frequent Mental Distress - White', 'Frequent Physical Distress',
       'Frequent Physical Distress - $25-$49,999',
       'Frequent Physical Distress - $50-$74,999',
       'Frequent Physical Distress - $75,000 or More',
       'Frequent Physical Distress - Ages 18-44',
       'Frequent Physical Distress - Ages 45-64',
       'Frequent Physical Distress - Ages 65+',
       'Frequent Physical Distress - American Indian/Alaskan Native',
       'Frequent Physical Distress - Asian',
       'Frequent Physical Distress - Black',
       'Frequent Physical Distress - College Grad',
       'Frequent Physical Distress - Female',
       'Frequent Physical Distress - Hawaiian/Pacific Islander',
       'Frequent Physical Distress - High School Grad',
       'Frequent Physical Distress - Hispanic',
       'Frequent Physical Distress - Less Than $25,000',
       'Frequent Physical Distress - Less Than High School',
       'Frequent Physical Distress - Male',
       'Frequent Physical Distress - Rural',
       'Frequent Physical Distress - Some College',
       'Frequent Physical Distress - Suburban',
       'Frequent Physical Distress - Urban',
       'Frequent Physical Distress - White', 'Fruits',
       'HC Coverage - $25-$49,999', 'HC Coverage - $50-$74,999',
       'HC Coverage - $75,000 or More', 'HC Coverage - 18-44',
       'HC Coverage - 45-64', 'HC Coverage - 65+',
       'HC Coverage - American Indian', 'HC Coverage - Asian',
       'HC Coverage - Black', 'HC Coverage - College Grad',
       'HC Coverage - Female', 'HC Coverage - Hawaiian PI',
       'HC Coverage - High School Grad', 'HC Coverage - Hispanic',
       'HC Coverage - Less Than $25,000', 'HC Coverage - Less Than HS',
       'HC Coverage - Male', 'HC Coverage - Rural',
       'HC Coverage - Some College', 'HC Coverage - Suburban',
       'HC Coverage - Urban', 'HC Coverage - White',
       'Health Care Coverage', 'Heart Attack',
       'Heart Attack - $25-$49,999', 'Heart Attack - $50-$74,999',
       'Heart Attack - $75,000 or More', 'Heart Attack - Ages 18-44',
       'Heart Attack - Ages 45-64', 'Heart Attack - Ages 65+',
       'Heart Attack - American Indian/Alaskan Native',
       'Heart Attack - Asian', 'Heart Attack - Black',
       'Heart Attack - College Grad', 'Heart Attack - Female',
       'Heart Attack - Hawaiian/Pacific Islander',
       'Heart Attack - High School Grad', 'Heart Attack - Hispanic',
       'Heart Attack - Less Than $25,000',
       'Heart Attack - Less Than High School', 'Heart Attack - Male',
       'Heart Attack - Rural', 'Heart Attack - Some College',
       'Heart Attack - Suburban', 'Heart Attack - Urban',
       'Heart Attack - White', 'Heart Disease',
       'Heart Disease - $25-$49,999', 'Heart Disease - $50-$74,999',
       'Heart Disease - $75,000 or More', 'Heart Disease - Ages 18-44',
       'Heart Disease - Ages 45-64', 'Heart Disease - Ages 65+',
       'Heart Disease - American Indian/Alaskan Native',
       'Heart Disease - Asian', 'Heart Disease - Black',
       'Heart Disease - College Grad', 'Heart Disease - Female',
       'Heart Disease - Hawaiian/Pacific Islander',
       'Heart Disease - High School Grad', 'Heart Disease - Hispanic',
       'Heart Disease - Less Than $25,000',
       'Heart Disease - Less Than High School', 'Heart Disease - Male',
       'Heart Disease - Rural', 'Heart Disease - Some College',
       'Heart Disease - Suburban', 'Heart Disease - Urban',
       'Heart Disease - White', 'High Blood Pressure',
       'High Blood Pressure - $25-$49,999',
       'High Blood Pressure - $50-$74,999',
       'High Blood Pressure - $75,000 or More',
       'High Blood Pressure - Ages 18-44',
       'High Blood Pressure - Ages 45-64',
       'High Blood Pressure - Ages 65+',
       'High Blood Pressure - American Indian/Alaskan Native',
       'High Blood Pressure - Asian', 'High Blood Pressure - Black',
       'High Blood Pressure - College Grad',
       'High Blood Pressure - Female',
       'High Blood Pressure - Hawaiian/Pacific Islander',
       'High Blood Pressure - High School Grad',
       'High Blood Pressure - Hispanic',
       'High Blood Pressure - Less Than $25,000',
       'High Blood Pressure - Less Than High School',
       'High Blood Pressure - Male', 'High Blood Pressure - Rural',
       'High Blood Pressure - Some College',
       'High Blood Pressure - Suburban', 'High Blood Pressure - Urban',
       'High Blood Pressure - White', 'High Cholesterol',
       'High Health Status', 'High Health Status - $25-$49,999',
       'High Health Status - $50-$74,999',
       'High Health Status - $75,000 or More',
       'High Health Status - Ages 18-44',
       'High Health Status - Ages 45-64', 'High Health Status - Ages 65+',
       'High Health Status - American Indian/Alaskan Native',
       'High Health Status - Asian', 'High Health Status - Black',
       'High Health Status - College Grad', 'High Health Status - Female',
       'High Health Status - Hawaiian/Pacific Islander',
       'High Health Status - High School Grad',
       'High Health Status - Hispanic',
       'High Health Status - Less Than $25,000',
       'High Health Status - Less Than High School',
       'High Health Status - Male', 'High Health Status - Rural',
       'High Health Status - Some College',
       'High Health Status - Suburban', 'High Health Status - Urban',
       'High Health Status - White', 'High School Graduation',
       'High School Graduation - American Indian/Alaska Native',
       'High School Graduation - Asian/Pacific Islander',
       'High School Graduation - Black',
       'High School Graduation - Hispanic',
       'High School Graduation - White', 'Immunization HPV Females',
       'Immunization HPV Females - Above Poverty',
       'Immunization HPV Females - Below Poverty',
       'Immunization HPV Females - Black',
       'Immunization HPV Females - Hispanic',
       'Immunization HPV Females - White', 'Immunization HPV Males',
       'Immunization HPV Males - Above Poverty',
       'Immunization HPV Males - Below Poverty',
       'Immunization HPV Males - Black',
       'Immunization HPV Males - Hispanic',
       'Immunization HPV Males - White', 'Immunizations - Adolescents',
       'Immunizations - Children', 'Income Disparity Ratio',
       'Income Inequality - Gini Index', 'Infant Mortality',
       'Infant Mortality - American Indian/Alaskan Native',
       'Infant Mortality - Asian', 'Infant Mortality - Black',
       'Infant Mortality - Hispanic',
       'Infant Mortality - Mother Ages 15-19',
       'Infant Mortality - Mother Ages 20-24',
       'Infant Mortality - Mother Ages 25-29',
       'Infant Mortality - Mother Ages 30-34',
       'Infant Mortality - Mother Ages 35-39',
       'Infant Mortality - Mother Ages 40-44', 'Infant Mortality - White',
       'Infectious Disease', 'Injury Deaths',
       'Injury Deaths - Ages 15-24', 'Injury Deaths - Ages 25-34',
       'Injury Deaths - Ages 35-44', 'Injury Deaths - Ages 45-54',
       'Injury Deaths - Ages 5-14', 'Injury Deaths - Ages 55-64',
       'Injury Deaths - Ages 65-74',
       'Injury Deaths - American Indian/Alaskan Native',
       'Injury Deaths - Asian/Pacific Islander', 'Injury Deaths - Black',
       'Injury Deaths - Female', 'Injury Deaths - Hispanic',
       'Injury Deaths - Male', 'Injury Deaths - White',
       'Insufficient Sleep', 'Insufficient Sleep - $25-$49,999',
       'Insufficient Sleep - $50-$74,999',
       'Insufficient Sleep - $75,000 or More',
       'Insufficient Sleep - Ages 18-44',
       'Insufficient Sleep - Ages 45-64', 'Insufficient Sleep - Ages 65+',
       'Insufficient Sleep - American Indian/Alaskan Native',
       'Insufficient Sleep - Asian', 'Insufficient Sleep - Black',
       'Insufficient Sleep - College Grad', 'Insufficient Sleep - Female',
       'Insufficient Sleep - Hawaiian/Pacific Islander',
       'Insufficient Sleep - High School Grad',
       'Insufficient Sleep - Hispanic',
       'Insufficient Sleep - Less Than $25,000',
       'Insufficient Sleep - Less Than High School',
       'Insufficient Sleep - Male', 'Insufficient Sleep - Rural',
       'Insufficient Sleep - Some College',
       'Insufficient Sleep - Suburban', 'Insufficient Sleep - Urban',
       'Insufficient Sleep - White', 'Low Birthweight',
       'Low Birthweight - Black/African American',
       'Low Birthweight - College Graduate',
       'Low Birthweight - High School Graduate',
       'Low Birthweight - Hispanic',
       'Low Birthweight - Less Than High School',
       'Low Birthweight - Mother Ages 15-19',
       'Low Birthweight - Mother Ages 20-24',
       'Low Birthweight - Mother Ages 25-29',
       'Low Birthweight - Mother Ages 30-34',
       'Low Birthweight - Mother Ages 35-39',
       'Low Birthweight - Mother Ages 40-44',
       'Low Birthweight - Some College', 'Low Birthweight - White',
       'Median Household Income', 'Meningococcal Immunizations',
       'Meningococcal Immunizations - Above Poverty',
       'Meningococcal Immunizations - Below Poverty',
       'Meningococcal Immunizations - Black',
       'Meningococcal Immunizations - Hispanic',
       'Meningococcal Immunizations - White', 'Obesity',
       'Obesity - $25-$49,999', 'Obesity - $50-$74,999',
       'Obesity - $75,000 or More', 'Obesity - Ages 18-44',
       'Obesity - Ages 45-64', 'Obesity - Ages 65+',
       'Obesity - American Indian/Alaskan Native', 'Obesity - Asian',
       'Obesity - Black', 'Obesity - College Grad', 'Obesity - Female',
       'Obesity - Hawaiian/Pacific Islander',

In [6]:
#'Below poverty threshold','Cancer Deaths','Cardiovascular Deaths','Cholesterol Check','Diabetes','Drug Deaths',

In [7]:
Unemployment_Rate=df2015[df2015['Measure Name']=='Unemployment Rate, Annual']

In [8]:
Unemployment_Rate.head()

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
35202,2015,2015 Annual,"Unemployment Rate, Annual",Alabama,40.0,6.8,0.481,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35203,2015,2015 Annual,"Unemployment Rate, Annual",Alaska,40.0,6.8,0.481,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35204,2015,2015 Annual,"Unemployment Rate, Annual",Arizona,42.0,6.9,0.561,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35205,2015,2015 Annual,"Unemployment Rate, Annual",Arkansas,26.0,6.1,-0.080,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35206,2015,2015 Annual,"Unemployment Rate, Annual",California,47.0,7.5,1.041,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014

In [9]:
Unemployment_Rate.isnull().any()

Edition         False
Report Type     False
Measure Name    False
State Name      False
Rank             True
Value           False
Score            True
Lower CI         True
Upper CI         True
Source          False
Source Year     False
dtype: bool

In [10]:
Unemployment_Rate.loc[Unemployment_Rate.isnull().any(axis=1)]

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
35202,2015,2015 Annual,"Unemployment Rate, Annual",Alabama,40.0,6.8,0.481,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35203,2015,2015 Annual,"Unemployment Rate, Annual",Alaska,40.0,6.8,0.481,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35204,2015,2015 Annual,"Unemployment Rate, Annual",Arizona,42.0,6.9,0.561,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35205,2015,2015 Annual,"Unemployment Rate, Annual",Arkansas,26.0,6.1,-0.080,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35206,2015,2015 Annual,"Unemployment Rate, Annual",California,47.0,7.5,1.041,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35207,2015,2015 Annual,"Unemployment Rate, Annual",Colorado,15.0,5.0,-0.961,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35208,2015,2015 Annual,"Unemployment Rate, Annual",Connecticut,37.0,6.6,0.320,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35209,2015,2015 Annual,"Unemployment Rate, Annual",Delaware,19.0,5.7,-0.400,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35210,2015,2015 Annual,"Unemployment Rate, Annual",Florida,30.0,6.3,0.080,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35211,2015,2015 Annual,"Unemployment Rate, Annual",Georgia,45.0,7.2,0.801,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35212,2015,2015 Annual,"Unemployment Rate, Annual",Hawaii,9.0,4.4,-1.442,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35213,2015,2015 Annual,"Unemployment Rate, Annual",Idaho,14.0,4.8,-1.121,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35214,2015,2015 Annual,"Unemployment Rate, Annual",Illinois,44.0,7.1,0.721,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35215,2015,2015 Annual,"Unemployment Rate, Annual",Indiana,25.0,6.0,-0.160,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35216,2015,2015 Annual,"Unemployment Rate, Annual",Iowa,9.0,4.4,-1.442,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35217,2015,2015 Annual,"Unemployment Rate, Annual",Kansas,11.0,4.5,-1.362,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35218,2015,2015 Annual,"Unemployment Rate, Annual",Kentucky,34.0,6.5,0.240,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35219,2015,2015 Annual,"Unemployment Rate, Annual",Louisiana,32.0,6.4,0.160,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35220,2015,2015 Annual,"Unemployment Rate, Annual",Maine,19.0,5.7,-0.400,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35221,2015,2015 Annual,"Unemployment Rate, Annual",Maryland,22.0,5.8,-0.320,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35222,2015,2015 Annual,"Unemployment Rate, Annual",Massachusetts,22.0,5.8,-0.320,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35223,2015,2015 Annual,"Unemployment Rate, Annual",Michigan,46.0,7.3,0.881,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35224,2015,2015 Annual,"Unemployment Rate, Annual",Minnesota,5.0,4.1,-1.682,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35225,2015,2015 Annual,"Unemployment Rate, Annual",Mississippi,49.0,7.8,1.282,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35226,2015,2015 Annual,"Unemployment Rate, Annual",Missouri,26.0,6.1,-0.080,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35227,2015,2015 Annual,"Unemployment Rate, Annual",Montana,13.0,4.7,-1.201,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35228,2015,2015 Annual,"Unemployment Rate, Annual",Nebraska,2.0,3.3,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35229,2015,2015 Annual,"Unemployment Rate, Annual",Nevada,49.0,7.8,1.282,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35230,2015,2015 Annual,"Unemployment Rate, Annual",New Hampshire,7.0,4.3,-1.522,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35231,2015,2015 Annual,"Unemployment Rate, Annual",New Jersey,37.0,6.6,0.320,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35232,2015,2015 Annual,"Unemployment Rate, Annual",New Mexico,34.0,6.5,0.240,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35233,2015,2015 Annual,"Unemployment Rate, Annual",New York,30.0,6.3,0.080,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35234,2015,2015 Annual,"Unemployment Rate, Annual",North Carolina,26.0,6.1,-0.080,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35235,2015,2015 Annual,"Unemployment Rate, Annual",North Dakota,1.0,2.8,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35236,2015,2015 Annual,"Unemployment Rate, Annual",Ohio,19.0,5.7,-0.400,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35237,2015,2015 Annual,"Unemployment Rate, Annual",Oklahoma,11.0,4.5,-1.362,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35238,2015,2015 Annual,"Unemployment Rate, Annual",Oregon,42.0,6.9,0.561,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35239,2015,2015 Annual,"Unemployment Rate, Annual",Pennsylvania,22.0,5.8,-0.320,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35240,2015,2015 Annual,"Unemployment Rate, Annual",Rhode Island,48.0,7.7,1.201,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35241,2015,2015 Annual,"Unemployment Rate, Annual",South Carolina,32.0,6.4,0.160,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35242,2015,2015 Annual,"Unemployment Rate, Annual",South Dakota,3.0,3.4,-2.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35243,2015,2015 Annual,"Unemployment Rate, Annual",Tennessee,39.0,6.7,0.400,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35244,2015,2015 Annual,"Unemployment Rate, Annual",Texas,16.0,5.1,-0.881,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35245,2015,2015 Annual,"Unemployment Rate, Annual",Utah,4.0,3.8,-1.922,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35246,2015,2015 Annual,"Unemployment Rate, Annual",Vermont,5.0,4.1,-1.682,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35247,2015,2015 Annual,"Unemployment Rate, Annual",Virginia,17.0,5.2,-0.801,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35248,2015,2015 Annual,"Unemployment Rate, Annual",Washington,29.0,6.2,0.000,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35249,2015,2015 Annual,"Unemployment Rate, Annual",West Virginia,34.0,6.5,0.240,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35250,2015,2015 Annual,"Unemployment Rate, Annual",Wisconsin,18.0,5.5,-0.561,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35251,2015,2015 Annual,"Unemployment Rate, Annual",Wyoming,7.0,4.3,-1.522,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35252,2015,2015 Annual,"Unemployment Rate, Annual",United States,NaN,6.2,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35253,2015,2015 Annual,"Unemployment Rate, Annual",District of Columbia,NaN,7.8,NaN,NaN,NaN,"U.S. Department of Labor, Bureau of Labor Stat...",2014

In [11]:
Unemployment_Rate = Unemployment_Rate.fillna(value=0)
Unemployment_Rate

,Edition,Report Type,Measure Name,State Name,Rank,Value,Score,Lower CI,Upper CI,Source,Source Year
35202,2015,2015 Annual,"Unemployment Rate, Annual",Alabama,40.0,6.8,0.481,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35203,2015,2015 Annual,"Unemployment Rate, Annual",Alaska,40.0,6.8,0.481,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35204,2015,2015 Annual,"Unemployment Rate, Annual",Arizona,42.0,6.9,0.561,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35205,2015,2015 Annual,"Unemployment Rate, Annual",Arkansas,26.0,6.1,-0.080,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35206,2015,2015 Annual,"Unemployment Rate, Annual",California,47.0,7.5,1.041,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35207,2015,2015 Annual,"Unemployment Rate, Annual",Colorado,15.0,5.0,-0.961,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35208,2015,2015 Annual,"Unemployment Rate, Annual",Connecticut,37.0,6.6,0.320,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35209,2015,2015 Annual,"Unemployment Rate, Annual",Delaware,19.0,5.7,-0.400,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35210,2015,2015 Annual,"Unemployment Rate, Annual",Florida,30.0,6.3,0.080,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35211,2015,2015 Annual,"Unemployment Rate, Annual",Georgia,45.0,7.2,0.801,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35212,2015,2015 Annual,"Unemployment Rate, Annual",Hawaii,9.0,4.4,-1.442,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35213,2015,2015 Annual,"Unemployment Rate, Annual",Idaho,14.0,4.8,-1.121,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35214,2015,2015 Annual,"Unemployment Rate, Annual",Illinois,44.0,7.1,0.721,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35215,2015,2015 Annual,"Unemployment Rate, Annual",Indiana,25.0,6.0,-0.160,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35216,2015,2015 Annual,"Unemployment Rate, Annual",Iowa,9.0,4.4,-1.442,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35217,2015,2015 Annual,"Unemployment Rate, Annual",Kansas,11.0,4.5,-1.362,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35218,2015,2015 Annual,"Unemployment Rate, Annual",Kentucky,34.0,6.5,0.240,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35219,2015,2015 Annual,"Unemployment Rate, Annual",Louisiana,32.0,6.4,0.160,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35220,2015,2015 Annual,"Unemployment Rate, Annual",Maine,19.0,5.7,-0.400,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35221,2015,2015 Annual,"Unemployment Rate, Annual",Maryland,22.0,5.8,-0.320,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35222,2015,2015 Annual,"Unemployment Rate, Annual",Massachusetts,22.0,5.8,-0.320,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35223,2015,2015 Annual,"Unemployment Rate, Annual",Michigan,46.0,7.3,0.881,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35224,2015,2015 Annual,"Unemployment Rate, Annual",Minnesota,5.0,4.1,-1.682,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35225,2015,2015 Annual,"Unemployment Rate, Annual",Mississippi,49.0,7.8,1.282,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35226,2015,2015 Annual,"Unemployment Rate, Annual",Missouri,26.0,6.1,-0.080,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35227,2015,2015 Annual,"Unemployment Rate, Annual",Montana,13.0,4.7,-1.201,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35228,2015,2015 Annual,"Unemployment Rate, Annual",Nebraska,2.0,3.3,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35229,2015,2015 Annual,"Unemployment Rate, Annual",Nevada,49.0,7.8,1.282,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35230,2015,2015 Annual,"Unemployment Rate, Annual",New Hampshire,7.0,4.3,-1.522,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35231,2015,2015 Annual,"Unemployment Rate, Annual",New Jersey,37.0,6.6,0.320,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35232,2015,2015 Annual,"Unemployment Rate, Annual",New Mexico,34.0,6.5,0.240,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35233,2015,2015 Annual,"Unemployment Rate, Annual",New York,30.0,6.3,0.080,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35234,2015,2015 Annual,"Unemployment Rate, Annual",North Carolina,26.0,6.1,-0.080,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35235,2015,2015 Annual,"Unemployment Rate, Annual",North Dakota,1.0,2.8,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35236,2015,2015 Annual,"Unemployment Rate, Annual",Ohio,19.0,5.7,-0.400,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35237,2015,2015 Annual,"Unemployment Rate, Annual",Oklahoma,11.0,4.5,-1.362,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35238,2015,2015 Annual,"Unemployment Rate, Annual",Oregon,42.0,6.9,0.561,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35239,2015,2015 Annual,"Unemployment Rate, Annual",Pennsylvania,22.0,5.8,-0.320,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35240,2015,2015 Annual,"Unemployment Rate, Annual",Rhode Island,48.0,7.7,1.201,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35241,2015,2015 Annual,"Unemployment Rate, Annual",South Carolina,32.0,6.4,0.160,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35242,2015,2015 Annual,"Unemployment Rate, Annual",South Dakota,3.0,3.4,-2.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35243,2015,2015 Annual,"Unemployment Rate, Annual",Tennessee,39.0,6.7,0.400,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35244,2015,2015 Annual,"Unemployment Rate, Annual",Texas,16.0,5.1,-0.881,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35245,2015,2015 Annual,"Unemployment Rate, Annual",Utah,4.0,3.8,-1.922,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35246,2015,2015 Annual,"Unemployment Rate, Annual",Vermont,5.0,4.1,-1.682,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35247,2015,2015 Annual,"Unemployment Rate, Annual",Virginia,17.0,5.2,-0.801,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35248,2015,2015 Annual,"Unemployment Rate, Annual",Washington,29.0,6.2,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35249,2015,2015 Annual,"Unemployment Rate, Annual",West Virginia,34.0,6.5,0.240,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35250,2015,2015 Annual,"Unemployment Rate, Annual",Wisconsin,18.0,5.5,-0.561,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35251,2015,2015 Annual,"Unemployment Rate, Annual",Wyoming,7.0,4.3,-1.522,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35252,2015,2015 Annual,"Unemployment Rate, Annual",United States,0.0,6.2,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014
35253,2015,2015 Annual,"Unemployment Rate, Annual",District of Columbia,0.0,7.8,0.000,0.0,0.0,"U.S. Department of Labor, Bureau of Labor Stat...",2014

In [12]:
Unemployment_Rate.count()

Edition         52
Report Type     52
Measure Name    52
State Name      52
Rank            52
Value           52
Score           52
Lower CI        52
Upper CI        52
Source          52
Source Year     52
dtype: int64

In [13]:
list(Unemployment_Rate.columns.values)

['Edition',
 'Report Type',
 'Measure Name',
 'State Name',
 'Rank',
 'Value',
 'Score',
 'Lower CI',
 'Upper CI',
 'Source',
 'Source Year']

In [14]:
Unemployment_Rate= Unemployment_Rate[["State Name",
                                "Edition", 
                              "Measure Name",
                              "Rank",
                              "Value"]]

In [15]:
Unemployment_Rate.head()

       State Name  Edition               Measure Name  Rank  Value
35202     Alabama     2015  Unemployment Rate, Annual  40.0    6.8
35203      Alaska     2015  Unemployment Rate, Annual  40.0    6.8
35204     Arizona     2015  Unemployment Rate, Annual  42.0    6.9
35205    Arkansas     2015  Unemployment Rate, Annual  26.0    6.1
35206  California     2015  Unemployment Rate, Annual  47.0    7.5

In [16]:
Unemployment_Rate.rename(columns = {'Rank' : 'Unemployment_Rate_Rank', 
                             'Value' : 'Unemployment_Rate_Value',
                            'State Name': 'State',
                            'Edition': 'Year'}, 
                  inplace = True)

C:\Users\steph\Anaconda3\lib\site-packages\pandas\core\frame.py:4025: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)

In [17]:
Unemployment_Rate.head()

,State,Year,Measure Name,Unemployment_Rate_Rank,Unemployment_Rate_Value
35202,Alabama,2015,"Unemployment Rate, Annual",40.0,6.8
35203,Alaska,2015,"Unemployment Rate, Annual",40.0,6.8
35204,Arizona,2015,"Unemployment Rate, Annual",42.0,6.9
35205,Arkansas,2015,"Unemployment Rate, Annual",26.0,6.1
35206,California,2015,"Unemployment Rate, Annual",47.0,7.5

In [18]:
Unemployment_Rate = Unemployment_Rate.drop('Measure Name',axis=1)

In [19]:
Unemployment_Rate.head()

            State  Year  Unemployment_Rate_Rank  Unemployment_Rate_Value
35202     Alabama  2015                    40.0                      6.8
35203      Alaska  2015                    40.0                      6.8
35204     Arizona  2015                    42.0                      6.9
35205    Arkansas  2015                    26.0                      6.1
35206  California  2015                    47.0                      7.5

In [20]:
Unemployment_Rate.to_csv(os.path.join("..","..","Data","Raw","America_Health_Rankings","2015 MidStep","Unemployment_Rate.csv"),index = False)